# Numpy Tutorials 001

In [1]:
#!pip install --upgrade numpy 

In [2]:
import numpy as np

In [12]:
arr10 = np.array([1,2,3,4])

In [8]:
arr10

array([1, 2, 3, 4])

In [9]:
type(arr10)

numpy.ndarray

In [10]:
arr10 * 3

array([ 3,  6,  9, 12])

In [11]:
3 * [1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

# Introduction to NumPy and Numpy Arrays.

In [13]:
import numpy as np

### Creating Arrays

In [14]:
mylist1d = [1,2,3,4,5]
mylist2d = [[1,2,3,4,5], [6,7,8,9]]
mylist3d = [[[1,2,3],[4,5,6], [7,8,9]]]

In [15]:
myarrzeros = np.zeros((3,3))

In [16]:
myarrzeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
myarrones = np.ones((3,3))

In [18]:
myarrones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
myarridentity = np.eye(3)

In [20]:
myarridentity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
myarreven = np.arange(0, 10, 2)

In [22]:
myarreven

array([0, 2, 4, 6, 8])

In [23]:
myarr3d = np.array(mylist3d)

In [24]:
myarr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [29]:
for i in myarr3d:
    for row in i:
        print(row)
        print("*"*10)
        for cell in row:
            print(cell)
            print("__________")

[1 2 3]
**********
1
__________
2
__________
3
__________
[4 5 6]
**********
4
__________
5
__________
6
__________
[7 8 9]
**********
7
__________
8
__________
9
__________


In [30]:
print(myarr3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [31]:
print(myarr3d.shape)

(1, 3, 3)


In [33]:
print(myarr3d.ndim)

3


In [34]:
print(myarr3d.size)

9


In [35]:
print(myarr3d.dtype)

int32


In [36]:
def myarray001(myarray):
    print(myarray.shape)
    print(myarray.ndim)
    print(myarray.size)
    print(myarray.dtype)
    

In [37]:
myarray001(myarr3d)

(1, 3, 3)
3
9
int32


In [42]:
def myarray002(myarray):
    print("Shape: " + str(myarray.shape))
    print("ndim: " + str(myarray.ndim))
    print("Size: " + str(myarray.size))
    print("DType: " + str(myarray.dtype))

In [43]:
myarray002(myarr3d)

Shape: (1, 3, 3)
ndim: 3
Size: 9
DType: int32


In [75]:
def myarray003(myarray):
    print("Shape: ", myarray.shape)
    print("ndim: ", myarray.ndim)
    print("Size: ", myarray.size)
    print("DType: ", myarray.dtype)

In [49]:
myarray003(myarr3d)

Shape:  (1, 3, 3)
ndim:  3
Size:  9
DType:  int32


In [54]:
def myarray004(myarray):
    print("Shape: ", myarray.shape)
    print("ndim: ", myarray.ndim)
    print("Size: ", myarray.size)
    print("DType: ", myarray.dtype)
    print("DType: ", myarray.dtype, 8, 9.9, "Saad", myarr3d, [1,2,3], (1,2,3))

In [55]:
myarray004(myarr3d)

Shape:  (1, 3, 3)
ndim:  3
Size:  9
DType:  int32
DType:  int32 8 9.9 Saad [[[1 2 3]
  [4 5 6]
  [7 8 9]]] [1, 2, 3] (1, 2, 3)


### How to import python data types into numpy array

In [56]:
mylist1d

[1, 2, 3, 4, 5]

In [57]:
mylist2d

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

In [58]:
mylist3d

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [59]:
mytuple1d = (1,2,3)

In [60]:
myset = {1,2,3,3}

In [61]:
myset

{1, 2, 3}

In [62]:
mydict = {'a':1, 'b':2}

In [63]:
myarray1d = np.array(mylist1d)

In [64]:
myarray1d

array([1, 2, 3, 4, 5])

In [65]:
type(myarray1d)

numpy.ndarray

In [66]:
myarray2d = np.array(mylist2d)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [67]:
mylist2d

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

In [69]:
mylist2d = [[1,2,3], [4,5,6]]

In [70]:
myarray2d = np.array(mylist2d)

In [71]:
myarray2d

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
for i in myarray2d:
    print(i)

[1 2 3]
[4 5 6]


In [73]:
myarray3d = np.array(mylist3d)

In [74]:
myarray3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [76]:
myarray003(myarray3d)

Shape:  (1, 3, 3)
ndim:  3
Size:  9
DType:  int32


In [77]:
myarraytup = np.array(mytuple1d)

In [78]:
mytuple1d

(1, 2, 3)

In [80]:
myarrayset = np.array(myset)

In [81]:
myarrayset

array({1, 2, 3}, dtype=object)

In [82]:
myarraydict = np.array(mydict)

In [83]:
myarraydict 

array({'a': 1, 'b': 2}, dtype=object)

In [84]:
myarray003(myarraydict)

Shape:  ()
ndim:  0
Size:  1
DType:  object


In [85]:
myarray003(myarrayset)

Shape:  ()
ndim:  0
Size:  1
DType:  object


### Numpy Array Operations

In [86]:
myarray1d + myarray1d

array([ 2,  4,  6,  8, 10])

In [87]:
myarray1d

array([1, 2, 3, 4, 5])

In [88]:
print(myarray1d + myarray1d)

[ 2  4  6  8 10]


In [89]:
print(myarray2d + myarray2d)

[[ 2  4  6]
 [ 8 10 12]]


In [90]:
myarray2d

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
print(myarray2d + myarray1d)

ValueError: operands could not be broadcast together with shapes (2,3) (5,) 

In [92]:
myarray2d

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
myarray1d

array([1, 2, 3, 4, 5])

In [94]:
myarray1d = np.array([1,2,3])

In [95]:
print(myarray2d + myarray1d)

[[2 4 6]
 [5 7 9]]


In [96]:
myarray2d

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
myarray1d

array([1, 2, 3])

In [98]:
myarray3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [99]:
print(myarray3d + myarray1d)

[[[ 2  4  6]
  [ 5  7  9]
  [ 8 10 12]]]


In [100]:
[1,2,3] + [1,2,3]

[1, 2, 3, 1, 2, 3]

In [101]:
myarray3d + 3

array([[[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [102]:
myarray3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [103]:
3 + (1,2,3)

TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

In [104]:
3 + {1,2,3}

TypeError: unsupported operand type(s) for +: 'int' and 'set'

In [105]:
3 + mydict

TypeError: unsupported operand type(s) for +: 'int' and 'dict'

In [106]:
mydict

{'a': 1, 'b': 2}

In [107]:
myarraydict + 3

TypeError: unsupported operand type(s) for +: 'dict' and 'int'

In [108]:
myarrayset + 3

TypeError: unsupported operand type(s) for +: 'set' and 'int'

#### Mulitplication

In [109]:
myarray1d 

array([1, 2, 3])

In [110]:
3 * myarray1d

array([3, 6, 9])

In [111]:
3 * myarray2d

array([[ 3,  6,  9],
       [12, 15, 18]])

In [112]:
3 * myarray3d

array([[[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]]])

In [113]:
myarray1d * myarray1d

array([1, 4, 9])

In [114]:
myarray1d

array([1, 2, 3])

In [115]:
myarray2d * myarray2d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [116]:
myarray3d * myarray3d

array([[[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]])

In [117]:
myarray1d * myarray2d

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [118]:
myarray1d

array([1, 2, 3])

In [119]:
myarray2d

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
myarray1d + myarray3d

array([[[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]]])

In [121]:
myarray2d + myarray3d

ValueError: operands could not be broadcast together with shapes (2,3) (1,3,3) 

In [122]:
myarray31d = myarray2d + myarray2d

In [123]:
myarray31d

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [125]:
mylist3dA = mylist2d + mylist2d

In [126]:
mylist3dA

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [127]:
my3dA = np.array(mylist3dA)

In [128]:
myarray2d * my3dA 

ValueError: operands could not be broadcast together with shapes (2,3) (4,3) 

In [129]:
myarray2d

array([[1, 2, 3],
       [4, 5, 6]])

# Numpy Intro part 2

In [130]:
arr1 = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [131]:
myarray003(arr1)

Shape:  (3, 3)
ndim:  2
Size:  9
DType:  int32


In [132]:
arr1[0]

array([1, 2, 3])

In [133]:
arr1[0][0]

1

In [134]:
arr1[1,2]

6

In [135]:
row = 1

In [136]:
col = 2

In [137]:
arr1[row, col]

6

In [138]:
arr1[1]

array([4, 5, 6])

In [139]:
arr1[0]

array([1, 2, 3])

In [140]:
arr1[2]

array([7, 8, 9])

In [141]:
arr1[:, 1]

array([2, 5, 8])

In [143]:
arr1[row, 1]

5

In [144]:
arr1[0:2, 1:2]

array([[2],
       [5]])

In [145]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
myarray1d

array([1, 2, 3])

In [147]:
arr2 = myarray1d* 2 

In [148]:
arr3 = myarray1d* 4 

In [149]:
arr3 = arr3 + 2

In [150]:
arr3

array([ 6, 10, 14])

In [151]:
arr2

array([2, 4, 6])

In [152]:
arrdp = np.dot(arr2, arr3)

In [153]:
arrdp

136

In [154]:
2*6 + 4*10 + 6*16

148

In [155]:
arr3

array([ 6, 10, 14])

In [156]:
arr2

array([2, 4, 6])

In [157]:
2*6 + 4*10 + 6*14

136

In [158]:
arrdp = np.dot(arr2, arr3)

In [159]:
arrdp

136

In [160]:
arr3

array([ 6, 10, 14])

In [161]:
arr3.reshape(3,1)

array([[ 6],
       [10],
       [14]])

##### useful array functions

In [162]:
arr2

array([2, 4, 6])

In [163]:
arr2.sum()

12

In [164]:
arr2.max()

6

In [165]:
arr2.min()

2

In [166]:
arr2.avg()

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [167]:
arr2.mean()

4.0

In [168]:
arr2.std()

1.632993161855452

# Troubleshooting multiplication

In [169]:
myarray2d * my3dA 

ValueError: operands could not be broadcast together with shapes (2,3) (4,3) 

In [170]:
my3dA

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [171]:
my3dA.shape

(4, 3)

In [172]:
myarray2d

array([[1, 2, 3],
       [4, 5, 6]])

In [173]:
myarray2d.shape

(2, 3)

In [174]:
myarray2d + my3dA

ValueError: operands could not be broadcast together with shapes (2,3) (4,3) 

In [175]:
myarray1d

array([1, 2, 3])

In [176]:
myarray1d.shape

(3,)

In [177]:
myarray1d + 3

array([4, 5, 6])

In [178]:
myarray1d * 3

array([3, 6, 9])

In [179]:
myarray1d + myarray1d

array([2, 4, 6])

In [180]:
myarray2d

array([[1, 2, 3],
       [4, 5, 6]])

In [181]:
myarray1d + myarray2d

array([[2, 4, 6],
       [5, 7, 9]])

In [182]:
myarray1d * myarray2d

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [183]:
myarray3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [184]:
myarray2d

array([[1, 2, 3],
       [4, 5, 6]])

In [185]:
myarray3d + myarray2d

ValueError: operands could not be broadcast together with shapes (1,3,3) (2,3) 

In [199]:
mya4 = [ 

    [1,2,3],
    [4,5,6],
    [1,2,3],
    [4,5,6] 
]

In [200]:
type(mya4)

list

In [201]:
myarr4 = np.array(mya4)

In [202]:
myarr4.shape

(4, 3)

In [203]:
mya4

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [204]:
myarray2d + mya4

ValueError: operands could not be broadcast together with shapes (2,3) (4,3) 

In [205]:
mya4b = [ 
[
    [1,2,3],
    [4,5,6]
],
[
    [1,2,3],
    [4,5,6] 
]
]

In [206]:
type(mya4b)

list

In [207]:
myarr4b = np.array(mya4b)

In [208]:
myarr4b.shape

(2, 2, 3)

In [209]:
myarr4b + myarray2d

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]]])

In [211]:
myarr4b * myarray2d

array([[[ 1,  4,  9],
        [16, 25, 36]],

       [[ 1,  4,  9],
        [16, 25, 36]]])

# NP Zeros

In [213]:
#import numpy as np
arrzeros = np.zeros((1,3))

In [214]:
arr0s = np.zeros(5)

In [215]:
arr0s

array([0., 0., 0., 0., 0.])

In [216]:
arrzeros

array([[0., 0., 0.]])

In [217]:
arr2dzeros = np.zeros((2,3))

In [218]:
arr2dzeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [220]:
arr3dzeros = np.zeros((3,3))

In [221]:
arr3dzeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [223]:
arrmultiDzeros = np.zeros((2,3,4))

In [224]:
arrmultiDzeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [225]:
farr = np.zeros((2,3), order='F')

In [226]:
carr = np.zeros((2,3), order='C')

In [227]:
farr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [228]:
carr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [229]:
type(farr)

numpy.ndarray

In [230]:
type(carr)

numpy.ndarray

# Lecture 12 NP ones

In [1]:
#import numpy as np

In [2]:
arr = np.ones(10)

<IPython.core.display.Javascript object>

In [3]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
arr2d = np.ones((2,3), dtype= int)

<IPython.core.display.Javascript object>

In [5]:
arr2d

array([[1, 1, 1],
       [1, 1, 1]])

# Complext ones

In [13]:
arrc = np.ones(5, dtype=complex)

<IPython.core.display.Javascript object>

In [14]:
arrc

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

In [17]:
arrc2d = np.ones((2,3), dtype=complex)

<IPython.core.display.Javascript object>

In [18]:
arrc2d

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])

In [19]:
arrc3d = np.ones((2,2,3), dtype=complex)

<IPython.core.display.Javascript object>

In [20]:
arrc3d

array([[[1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j]],

       [[1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j]]])

In [21]:
arronesF = np.ones((2,3), dtype=int, order='F')

<IPython.core.display.Javascript object>

In [23]:
arronesC = np.ones((2,3), dtype = int, order='C')

<IPython.core.display.Javascript object>

In [24]:
arronesF

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
arronesC

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
dt = np.dtype([('x', 'int32'), ('y', 'float64')])

<IPython.core.display.Javascript object>

In [27]:
arr = np.ones(3, dtype=dt)

<IPython.core.display.Javascript object>

In [28]:
arr

array([(1, 1.), (1, 1.), (1, 1.)], dtype=[('x', '<i4'), ('y', '<f8')])

# Numpy arange function

In [29]:
#numpy.arange([start,] stop, [step,] dtype=None)

In [30]:
import numpy as np

In [31]:
arng1 = np.arange(10)

In [32]:
arng1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arng100 = np.arange(100)

In [34]:
arng100

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [35]:
arng2 = np.arange(10,2)

In [36]:
arng2

array([], dtype=int32)

In [37]:
arng2 = np.arange(10:2)

SyntaxError: invalid syntax (2963385560.py, line 1)

In [38]:
arng2=np.arange(,10,2)

SyntaxError: invalid syntax (2237557754.py, line 1)

In [39]:
arng2=np.arange(:10, 2)

SyntaxError: invalid syntax (2872407980.py, line 1)

In [40]:
arng2 = np.arange(0,10,2)

In [41]:
arng2

array([0, 2, 4, 6, 8])

In [42]:
arng5 = np.arange(0, 26, 5)

In [43]:
arng5

array([ 0,  5, 10, 15, 20, 25])

In [44]:
arng5_2_3 = arng5.reshape(2,3)

In [45]:
arng5_2_3

array([[ 0,  5, 10],
       [15, 20, 25]])

In [46]:
arr3 = np.arange(0,30, 3)

In [47]:
arr3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [48]:
arr4 = np.arange(0, -100, -1)

In [49]:
arr4

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25,
       -26, -27, -28, -29, -30, -31, -32, -33, -34, -35, -36, -37, -38,
       -39, -40, -41, -42, -43, -44, -45, -46, -47, -48, -49, -50, -51,
       -52, -53, -54, -55, -56, -57, -58, -59, -60, -61, -62, -63, -64,
       -65, -66, -67, -68, -69, -70, -71, -72, -73, -74, -75, -76, -77,
       -78, -79, -80, -81, -82, -83, -84, -85, -86, -87, -88, -89, -90,
       -91, -92, -93, -94, -95, -96, -97, -98, -99])

In [50]:
arr6 = np.arange(0, 100, -1)

In [51]:
arr6

array([], dtype=int32)

In [52]:
arr6 = np.arange(100, 0, -1)

In [53]:
arr6

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [56]:
arr7 = np.arange(0, 20, .3)

In [57]:
arr7

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8,  2.1,  2.4,  2.7,  3. ,
        3.3,  3.6,  3.9,  4.2,  4.5,  4.8,  5.1,  5.4,  5.7,  6. ,  6.3,
        6.6,  6.9,  7.2,  7.5,  7.8,  8.1,  8.4,  8.7,  9. ,  9.3,  9.6,
        9.9, 10.2, 10.5, 10.8, 11.1, 11.4, 11.7, 12. , 12.3, 12.6, 12.9,
       13.2, 13.5, 13.8, 14.1, 14.4, 14.7, 15. , 15.3, 15.6, 15.9, 16.2,
       16.5, 16.8, 17.1, 17.4, 17.7, 18. , 18.3, 18.6, 18.9, 19.2, 19.5,
       19.8])

In [58]:
arr8 = np.arange(0, 100, dtype=float)

In [59]:
arr8

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [60]:
x = np.arange(0, 2*np.pi, 0.1)

In [61]:
y = np.sin(x)

In [62]:
for i in range(5):
    print(f"x={x[i]:.1f}, y={y[i]:.3f}")

x=0.0, y=0.000
x=0.1, y=0.100
x=0.2, y=0.199
x=0.3, y=0.296
x=0.4, y=0.389


# np.linspace

In [64]:
import numpy as np

In [65]:
arr_lin1 = np.linspace(0, 10, num=20)

In [66]:
arr_lin1

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [69]:
arr_lin1.round(5)

array([ 0.     ,  0.52632,  1.05263,  1.57895,  2.10526,  2.63158,
        3.15789,  3.68421,  4.21053,  4.73684,  5.26316,  5.78947,
        6.31579,  6.84211,  7.36842,  7.89474,  8.42105,  8.94737,
        9.47368, 10.     ])

In [70]:
arr_lin2 = np.linspace(0, -10, num= 30)

In [71]:
arr_lin2 

array([  0.        ,  -0.34482759,  -0.68965517,  -1.03448276,
        -1.37931034,  -1.72413793,  -2.06896552,  -2.4137931 ,
        -2.75862069,  -3.10344828,  -3.44827586,  -3.79310345,
        -4.13793103,  -4.48275862,  -4.82758621,  -5.17241379,
        -5.51724138,  -5.86206897,  -6.20689655,  -6.55172414,
        -6.89655172,  -7.24137931,  -7.5862069 ,  -7.93103448,
        -8.27586207,  -8.62068966,  -8.96551724,  -9.31034483,
        -9.65517241, -10.        ])

In [73]:
arr_lin3 = arr_lin2.reshape(3, 10)

In [74]:
arr_lin3

array([[  0.        ,  -0.34482759,  -0.68965517,  -1.03448276,
         -1.37931034,  -1.72413793,  -2.06896552,  -2.4137931 ,
         -2.75862069,  -3.10344828],
       [ -3.44827586,  -3.79310345,  -4.13793103,  -4.48275862,
         -4.82758621,  -5.17241379,  -5.51724138,  -5.86206897,
         -6.20689655,  -6.55172414],
       [ -6.89655172,  -7.24137931,  -7.5862069 ,  -7.93103448,
         -8.27586207,  -8.62068966,  -8.96551724,  -9.31034483,
         -9.65517241, -10.        ]])

In [75]:
arr_lin4 = np.linspace(0, 15, num=21, endpoint=True)

In [76]:
arr_lin4

array([ 0.  ,  0.75,  1.5 ,  2.25,  3.  ,  3.75,  4.5 ,  5.25,  6.  ,
        6.75,  7.5 ,  8.25,  9.  ,  9.75, 10.5 , 11.25, 12.  , 12.75,
       13.5 , 14.25, 15.  ])

In [77]:
arr_lin5 = np.linspace(0, 15, num=21, endpoint=False)

In [78]:
arr_lin5

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ,
       10.71428571, 11.42857143, 12.14285714, 12.85714286, 13.57142857,
       14.28571429])

In [79]:
arr_lin6 = np.linspace(0, 15, num=21, endpoint=True, retstep=True)

In [80]:
arr_lin6 

(array([ 0.  ,  0.75,  1.5 ,  2.25,  3.  ,  3.75,  4.5 ,  5.25,  6.  ,
         6.75,  7.5 ,  8.25,  9.  ,  9.75, 10.5 , 11.25, 12.  , 12.75,
        13.5 , 14.25, 15.  ]),
 0.75)

In [81]:
arr_lin6 = np.linspace(0, 15, num=21, endpoint=False, retstep=True)

In [82]:
arr_lin6

(array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
         3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
         7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ,
        10.71428571, 11.42857143, 12.14285714, 12.85714286, 13.57142857,
        14.28571429]),
 0.7142857142857143)

In [83]:
14.28571429  + 0.7142857142857143

15.000000004285713

In [84]:
arr_lin7 = np.linspace(3.4, 15, num=21, endpoint=False, retstep=True)

In [85]:
arr_lin7

(array([ 3.4       ,  3.95238095,  4.5047619 ,  5.05714286,  5.60952381,
         6.16190476,  6.71428571,  7.26666667,  7.81904762,  8.37142857,
         8.92380952,  9.47619048, 10.02857143, 10.58095238, 11.13333333,
        11.68571429, 12.23809524, 12.79047619, 13.34285714, 13.8952381 ,
        14.44761905]),
 0.5523809523809524)

In [86]:
arr_lin8 = np.linspace(3.4, 15, num=21, endpoint=False, retstep=True, dtype=float)

In [87]:
arr_lin9 = np.linspace(3.4, 15, num=21, endpoint=False, retstep=True, dtype=int)

In [88]:
arr_lin9

(array([ 3,  3,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9, 10, 10, 11, 11, 12,
        12, 13, 13, 14]),
 0.5523809523809524)

In [89]:
arr_lin8 = np.linspace(3.4, 15, num=21, endpoint=False, retstep=True, dtype=decimal)

NameError: name 'decimal' is not defined

In [92]:
arr_lin8 = np.linspace(3.4, 15, num=21, endpoint=False, retstep=True, dtype=float64)

NameError: name 'float64' is not defined

# Lecture 15: Numpy.shape

In [93]:
import numpy as np

In [97]:
sharr1 = np.array(())

In [98]:
sharr1

array([], dtype=float64)

In [99]:
sharr1.shape

(0,)

In [100]:
sharr1.size

0

In [101]:
sharr2 = np.array(2)

In [102]:
sharr2

array(2)

In [103]:
sharr2.shape

()

In [109]:
type(sharr2)

numpy.ndarray

In [104]:
for i in sharr2:
    print(i)

TypeError: iteration over a 0-d array

In [105]:
sharr3 = np.array([2])

In [106]:
sharr3

array([2])

In [107]:
for i in sharr3:
    print(i)

2


In [108]:
sharr3.shape

(1,)

In [110]:
sharr3.size

1

In [111]:
sharr4 = np.array([1,2,3])

In [112]:
sharr4

array([1, 2, 3])

In [113]:
sharr4.size

3

In [114]:
sharr4.shape

(3,)

In [115]:
for i in sharr4:
    print(i)

1
2
3


In [116]:
sharr5 = np.array([1,2,3], [1,2,3])

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [117]:
sharr5 = np.array([[1,2,3], [1,2,3]])

In [118]:
sharr5

array([[1, 2, 3],
       [1, 2, 3]])

In [120]:
for i in sharr5[0]:
    print(i)

1
2
3


In [121]:
sharr5

array([[1, 2, 3],
       [1, 2, 3]])

In [122]:
sharr5[0]

array([1, 2, 3])

In [123]:
sharr5[1]

array([1, 2, 3])

In [124]:
sharr5.shape

(2, 3)

In [125]:
sharr6 = np.array([[1,2,3], [2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

NxM . MxN 

In [126]:
#3x3 X 2x3 
#1x3 X 3x3 

In [128]:
arr_md = np.arange(10)

# Reshape

In [129]:
arr_md 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
arr_md.shape

(10,)

In [133]:
arr_md = np.arange(10).reshape(2, 1)

ValueError: cannot reshape array of size 10 into shape (2,1)

In [134]:
arr_md = np.arange(10).reshape(2, 5)

In [135]:
arr_md


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
arr_md.shape

(2, 5)

In [151]:
arr_md.ndim

2

In [137]:
arr_3md = np.arange(27).reshape(3,3,3)

In [138]:
arr_3md

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [140]:
arr_3md.shape

(3, 3, 3)

In [150]:
arr_3md.ndim

3

In [145]:
arr_4md = np.arange(16).reshape(2,2,2,2)

In [146]:
arr_4md

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [148]:
arr_4md.shape

(2, 2, 2, 2)

In [149]:
arr_4md.ndim

4

In [152]:
arr_5d = np.arange(32).reshape(2,2,2,2,2)

In [153]:
arr_5d

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [154]:
arr_5d.shape

(2, 2, 2, 2, 2)

In [155]:
arr_5d.ndim

5

# Lecture 16 numpy dtype 

In [156]:
arrdt = np.arange(10)

In [157]:
arrdt

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
arrdt.shape

(10,)

In [159]:
arrdt.size

10

In [160]:
arrdt.ndim

1

In [161]:
arrdt.dtype

dtype('int32')

In [162]:
arrchardt = np.array(['a', 'b', 'c', 'd', 'f'])

In [163]:
arrchardt

array(['a', 'b', 'c', 'd', 'f'], dtype='<U1')

In [164]:
arrchardt.dtype

dtype('<U1')

In [171]:
arrchardt = np.array(['acb', 'bcc', 'ccc', 'dcd', 'ffdddc'])

In [172]:
arrchardt

array(['acb', 'bcc', 'ccc', 'dcd', 'ffdddc'], dtype='<U6')

In [173]:
arrchardt.dtype

dtype('<U6')

In [174]:
arrchardt2 = np.array([1.1, 2.3, 4.4])

In [175]:
arrchardt2.dtype

dtype('float64')

In [178]:
from numpy import *
import numpy as np

In [180]:
arrfloat32 = np.array([1.1, 2.3, 4.4], dtype=np.float32)

In [181]:
arrfloat32

array([1.1, 2.3, 4.4], dtype=float32)

In [183]:
arrfloat16 = np.array([1.1, 2.3, 4.4], dtype=np.float16)

In [184]:
arrcomplext = np.array([1.1, 2.3, 4.4], dtype = complex)

In [185]:
arrcomplext

array([1.1+0.j, 2.3+0.j, 4.4+0.j])

# Numpy Size

In [186]:
arr1 = np.arange(9)

In [187]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [189]:
arr1.size

9

In [190]:
np.size(arr1)

9

In [191]:
arr2 = np.arange(0, 10).reshape(2,5)

In [192]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [193]:
arr2.size

10

In [196]:
arr2.shape[0] * arr2.shape[1]

10

In [197]:
arr2.shape

(2, 5)

In [198]:
arr3 = np.arange(0, 27).reshape(3,3,3)

In [199]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [200]:
arr3.size

27

In [201]:
arr3.shape

(3, 3, 3)

In [202]:
arr3.shape[0]*arr3.shape[1]*arr3.shape[2]

27

# numpy ndim (dimensions)

In [203]:
import numpy as np

In [205]:
arr1 = np.array(1)

In [206]:
arr1

array(1)

In [207]:
arr1.ndim

0

In [208]:
np.ndim(arr1)

0

In [209]:
arr2 = np.array([])

In [210]:
arr2

array([], dtype=float64)

In [211]:
arr2.ndim

1

In [212]:
arr3 = np.array([1,2,3])

In [213]:
arr3.ndim

1

In [214]:
np.ndim(arr3)

1

In [215]:
arr2d = np.array([[1,2,3], [4,5,6]])

In [216]:
arr2d.ndim

2

In [217]:
arr2d2 = np.arange(10).reshape(2,5)

In [218]:
arr2d2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [219]:
arr2d2.ndim

2

In [220]:
arr3d = np.arange(27).reshape(3,3,3)

In [221]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [222]:
arr3d.ndim

3

In [223]:
np.ndim(arr3d)

3

In [224]:
arr4d = np.arange(16).reshape(2,2,2,2)

In [225]:
arr4d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [226]:
arr4d.ndim

4

In [227]:
np.ndim(arr4d)

4

In [228]:
arr5d = np.arange(32).reshape(2,2,2,2,2)

In [229]:
arr5d

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [230]:
arr5d.ndim

5

# Numpy.eye or Identity Matrix

In [246]:
import numpy as np

In [247]:
ey1 = np.eye(3)

In [248]:
ey1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [249]:
ey1.dtype

dtype('float64')

In [256]:
ey2 = np.eye(3, dtype='int8')

In [257]:
ey2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [258]:
ey2.dtype

dtype('int8')

In [259]:
#M . M-1 = I 

In [265]:
ar3 = np.array([[2, 4, 9],
       [11, 2, 5],
       [5, 3, 7]])

In [266]:
ar3

array([[ 2,  4,  9],
       [11,  2,  5],
       [ 5,  3,  7]])

In [267]:
ar3i = np.linalg.inv(ar3)

In [268]:
ar3i

array([[  0.33333333,   0.33333333,  -0.66666667],
       [ 17.33333333,  10.33333333, -29.66666667],
       [ -7.66666667,  -4.66666667,  13.33333333]])

In [269]:
ar3i * ar3

array([[   0.66666667,    1.33333333,   -6.        ],
       [ 190.66666667,   20.66666667, -148.33333333],
       [ -38.33333333,  -14.        ,   93.33333333]])

In [270]:
ar3 * ar3i

array([[   0.66666667,    1.33333333,   -6.        ],
       [ 190.66666667,   20.66666667, -148.33333333],
       [ -38.33333333,  -14.        ,   93.33333333]])

In [271]:
ar3 @ ar3i 

array([[ 1.00000000e+00, -4.44089210e-15,  1.77635684e-14],
       [ 1.77635684e-15,  1.00000000e+00,  3.55271368e-15],
       [-8.88178420e-15, -9.76996262e-15,  1.00000000e+00]])

In [272]:
np.dot(ar3i, ar3)

array([[ 1.00000000e+00,  1.99840144e-15,  3.77475828e-15],
       [ 1.06581410e-14,  1.00000000e+00,  3.55271368e-15],
       [-1.06581410e-14, -3.55271368e-15,  1.00000000e+00]])

In [273]:
np.matmul(ar3, ar3i)

array([[ 1.00000000e+00, -4.44089210e-15,  1.77635684e-14],
       [ 1.77635684e-15,  1.00000000e+00,  3.55271368e-15],
       [-8.88178420e-15, -9.76996262e-15,  1.00000000e+00]])

In [276]:
arey4 = np.eye(8,8)

In [277]:
arey4

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [278]:
ar_ey4 = np.eye(8,8, dtype='int8', order='C')

In [279]:
ar_ey4

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [290]:
ar_ey5 = np.eye(8,M=6, k=-1, dtype='int8', order='C')

In [291]:
ar_ey5 

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [292]:
ar3  

array([[ 2,  4,  9],
       [11,  2,  5],
       [ 5,  3,  7]])

In [293]:
ar3i

array([[  0.33333333,   0.33333333,  -0.66666667],
       [ 17.33333333,  10.33333333, -29.66666667],
       [ -7.66666667,  -4.66666667,  13.33333333]])

In [294]:
2 * .3333

0.6666

In [295]:
4 * .33333

1.33332

In [296]:
9 * -0.66666667

-6.00000003

In [297]:
ar3 * ar3i

array([[   0.66666667,    1.33333333,   -6.        ],
       [ 190.66666667,   20.66666667, -148.33333333],
       [ -38.33333333,  -14.        ,   93.33333333]])

In [298]:
ar3 + ar3i

array([[  2.33333333,   4.33333333,   8.33333333],
       [ 28.33333333,  12.33333333, -24.66666667],
       [ -2.66666667,  -1.66666667,  20.33333333]])

In [299]:
list1 = [[1,2], [2,3]]
list2 = [[1,2], [2,3]]

In [300]:
list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

In [301]:
list1 + list2

[[1, 2], [2, 3], [1, 2], [2, 3]]

In [302]:
myarray = np.array(list1)

In [303]:
myarray + myarray

array([[2, 4],
       [4, 6]])

In [304]:
myarray * myarray

array([[1, 4],
       [4, 9]])

# np.diag 

In [305]:
import numpy as np

In [307]:
ar3  

array([[ 2,  4,  9],
       [11,  2,  5],
       [ 5,  3,  7]])

In [310]:
arr4 = np.diag(ar3)

In [311]:
arr4

array([2, 2, 7])

In [312]:
arr4.size

3

In [314]:
arr4.dtype

dtype('int32')

In [315]:
arr4.shape

(3,)

In [316]:
arr5 = np.diag(arr4)

In [317]:
arr5

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 7]])

# numpy.random Random

In [1]:
import numpy as np

In [12]:
x = np.random.random()
print(x)

0.8060127582719688


In [20]:
arr_random= np.random.random((3,3))
arr_random

array([[0.88872146, 0.9723656 , 0.11215018],
       [0.89173083, 0.95274754, 0.30581341],
       [0.96933552, 0.31739038, 0.65412056]])

In [21]:
type(arr_random)

numpy.ndarray

## Random Integers

In [32]:
x = np.random.randint(1, 100)
x
type(x)

int

In [34]:
x = np.random.randint(1, 50, size=1)
print(x)
print(type(x))

[4]
<class 'numpy.ndarray'>


In [36]:
arr_rand_int = np.random.randint(1, 1000, size=5)

In [39]:
print(arr_rand_int)
print(arr_rand_int.ndim)

[ 71 563 660 117 793]
1


In [48]:
arr_i_2d = np.random.randint(1, 55, size=(2,2))
arr_i_2d

array([[12, 30],
       [22, 24]])

In [49]:
arr_i_3d = np.random.randint(1, 55, size=(2,2,2))
arr_i_3d

array([[[21, 29],
        [37, 53]],

       [[36, 26],
        [ 8, 15]]])

In [50]:
arr_i_3d.ndim

3

In [51]:
type(arr_i_3d)

numpy.ndarray

# choice

In [52]:
countries = ['Canada', 'USA', 'Mexico', 'France', 'Italy', 'Germany']

In [72]:
mychoice = np.random.choice(countries)
mychoice

'Germany'

In [68]:
choices = np.random.choice(countries, size=15)

In [69]:
choices

array(['Germany', 'Mexico', 'Italy', 'France', 'Germany', 'Italy', 'USA',
       'Mexico', 'Canada', 'Germany', 'Canada', 'USA', 'Italy', 'France',
       'France'], dtype='<U7')

In [76]:
mylist = []
for i in range(15):
    print( np.random.choice(countries))
    mylist.append(np.random.choice(countries))

Mexico
Mexico
Italy
France
Canada
Mexico
France
USA
USA
USA
France
France
France
Mexico
Canada


In [77]:
mylist

['Italy',
 'Mexico',
 'Canada',
 'Germany',
 'Mexico',
 'Germany',
 'Canada',
 'USA',
 'Germany',
 'Mexico',
 'Germany',
 'Mexico',
 'France',
 'Canada',
 'Canada']

In [78]:
uniq=np.random.choice(countries, size=5, replace=False)

In [79]:
uniq

array(['USA', 'Germany', 'Canada', 'Mexico', 'France'], dtype='<U7')

In [83]:
uniq=np.random.choice(countries, size=7, replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'

# shuffle

In [84]:
co = np.array(countries)

In [85]:
co

array(['Canada', 'USA', 'Mexico', 'France', 'Italy', 'Germany'],
      dtype='<U7')

In [99]:
np.random.shuffle(co)
print(co)

['Canada' 'Germany' 'Mexico' 'France' 'USA' 'Italy']


In [105]:
shu = np.random.permutation(co)
co

array(['Canada', 'Germany', 'Mexico', 'France', 'USA', 'Italy'],
      dtype='<U7')

In [106]:
shu

array(['Germany', 'Canada', 'USA', 'Italy', 'France', 'Mexico'],
      dtype='<U7')

In [110]:
def myarray004(myarray):
    print("Shape: ", myarray.shape)
    print("ndim: ", myarray.ndim)
    print("Size: ", myarray.size)
    print("DType: ", myarray.dtype)
     

In [111]:
myarray004(shu)

Shape:  (6,)
ndim:  1
Size:  6
DType:  <U7


# Default_rng()

In [112]:
import numpy as np

In [113]:
np.__version__

'1.26.4'

In [119]:
np.random.default_rng()

Generator(PCG64) at 0x1613DA6C580

In [120]:
arr_rng = np.random.default_rng()

In [121]:
arr_rng

Generator(PCG64) at 0x1613D88F5A0

In [122]:
type(arr_rng)

numpy.random._generator.Generator

In [127]:
#generate a float number using default_rng():
myf = arr_rng.random()

In [128]:
myf

0.15761071019455686

In [129]:
myf1 = arr_rng.random(3)

In [130]:
myf1

array([0.93194119, 0.88273734, 0.21864983])

In [131]:
type(myf1)

numpy.ndarray

In [132]:
def myarray004(myarray):
    print("Shape: ", myarray.shape)
    print("ndim: ", myarray.ndim)
    print("Size: ", myarray.size)
    print("DType: ", myarray.dtype)

In [133]:
myarray004(myf1)

Shape:  (3,)
ndim:  1
Size:  3
DType:  float64


In [142]:
myint1 = arr_rng.integers(3)

In [143]:
myint1

0

In [144]:
myint2 = arr_rng.integers(1, 100, size=12)

In [145]:
myint2

array([27, 37, 41, 27, 74,  3, 99, 43, 40, 34, 69, 55], dtype=int64)

In [146]:
myint3 = arr_rng.integers(1, 100, size=12, dtype='int64')

In [147]:
myint3

array([29, 81, 54, 66, 12,  8,  3, 33, 59, 58, 60,  1], dtype=int64)

In [149]:
myint4 = arr_rng.integers(1, 100, size=12, dtype='int32')

In [150]:
myint4

array([42, 68, 15, 97, 79, 70, 66, 88, 62,  8, 51, 42])

In [151]:
myint5 = arr_rng.integers(1, 100, size=12, dtype='int16')

In [152]:
myint5

array([25, 26, 79, 29, 10, 15,  1, 92, 25,  5, 73, 40], dtype=int16)

In [153]:
myint6 = arr_rng.integers(1, 100, size=12, dtype='int8')

In [155]:
myint6

array([42,  2, 65, 39, 60, 73, 51, 86, 69, 23, 19, 38], dtype=int8)

In [157]:
myint6 = arr_rng.integers(1, 1000, size=12, dtype='int16')

In [158]:
myint6

array([815, 232, 574, 965, 351, 308, 598, 850, 156, 542,  36, 734],
      dtype=int16)

In [167]:
myf1 = arr_rng.random(size=(5,5), dtype='float32')

In [163]:
myf1

array([[0.09325683, 0.18794984, 0.44665092, 0.46546954, 0.3099451 ],
       [0.9872903 , 0.8831625 , 0.08810794, 0.93986404, 0.64225274],
       [0.67038023, 0.04597002, 0.5627006 , 0.47457087, 0.8779608 ],
       [0.5285585 , 0.96596086, 0.3174386 , 0.86624837, 0.82464886],
       [0.39526772, 0.06121546, 0.9850871 , 0.33989155, 0.16487789]],
      dtype=float32)

In [168]:
myarray004(myf1)

Shape:  (5, 5)
ndim:  2
Size:  25
DType:  float32


In [172]:
myf3d = arr_rng.random(size=(3,5,5), dtype='float64')

In [173]:
myf3d

array([[[0.18376276, 0.60392824, 0.45564562, 0.41967676, 0.81649749],
        [0.41989546, 0.27422736, 0.0254394 , 0.40657992, 0.06878082],
        [0.02585672, 0.4702922 , 0.80746621, 0.5087388 , 0.16903104],
        [0.27725832, 0.37582822, 0.94756367, 0.58617879, 0.83270845],
        [0.48149972, 0.62469672, 0.03201491, 0.56593883, 0.31994208]],

       [[0.87858279, 0.27053364, 0.51555319, 0.26256645, 0.61957514],
        [0.84415247, 0.99285086, 0.44630673, 0.86313678, 0.5792572 ],
        [0.64355018, 0.88681438, 0.71158083, 0.02781926, 0.04694132],
        [0.54800726, 0.68261419, 0.64413043, 0.89768143, 0.89692417],
        [0.33552228, 0.46695418, 0.160584  , 0.74837519, 0.20168485]],

       [[0.2160957 , 0.59657304, 0.70530785, 0.10794187, 0.25043267],
        [0.29808947, 0.4758943 , 0.76780529, 0.99997149, 0.06032   ],
        [0.01522212, 0.49712027, 0.2953388 , 0.7814303 , 0.26187751],
        [0.93512162, 0.35569696, 0.68931857, 0.72338439, 0.47555004],
        [0.20601

In [174]:
myarray004(myf3d)

Shape:  (3, 5, 5)
ndim:  3
Size:  75
DType:  float64


In [177]:
myint3d = arr_rng.integers(3,5,5)

In [178]:
myint3d

array([3, 3, 3, 4, 4], dtype=int64)

In [183]:
myint3d = arr_rng.integers(1, 50, size=(5,5), dtype='int8')

In [184]:
myint3d

array([[39, 18, 17, 39, 46],
       [48, 31,  9, 37, 18],
       [10, 25, 44, 40, 41],
       [ 9, 20, 43, 44, 39],
       [33, 34,  9, 29, 35]], dtype=int8)

In [192]:
#Normal Distribution (mean=0, std=1)
print(arr_rng.normal(size=(3,3)))

[[ 0.72434701 -2.95481189 -0.08412396]
 [ 0.72145709  0.24303822 -0.38598749]
 [-0.89461672 -0.17428606 -1.94996688]]


In [193]:
#Uniform distribution [low, high]
arr_rng.uniform(1, 10, size=(3,3,3))

array([[[1.36924246, 2.18364071, 3.14037673],
        [6.30353373, 4.19101402, 7.06229168],
        [7.04762435, 6.2004899 , 7.3992277 ]],

       [[2.86154651, 5.30341847, 9.8965392 ],
        [3.55343006, 1.68288985, 6.65712503],
        [4.28679816, 4.56419336, 2.00473477]],

       [[1.43538398, 4.13584988, 4.20919023],
        [4.26705263, 3.84555298, 8.36570891],
        [8.66445715, 3.30603383, 4.46242666]]])

In [195]:
arr_rng.choice(['Chicago', 'Boston', 'Vegas'], size=(2,2))

array([['Chicago', 'Chicago'],
       ['Chicago', 'Vegas']], dtype='<U7')

In [196]:
#reproducible arrays:
arr_rng1 = np.random.default_rng(seed=42)
print(arr_rng1.integers(0,10, 3))

[0 7 6]


In [209]:
arr_rng1 = np.random.default_rng(seed=100)
print(arr_rng1.integers(0,10, 3))

[7 8 1]


In [211]:
#Saving Loading state
#save state
state = arr_rng1.bit_generator.state

In [212]:
state

{'bit_generator': 'PCG64',
 'state': {'state': 164404244729103591598495580972637239091,
  'inc': 30008503642980956324491363429807189605},
 'has_uint32': 1,
 'uinteger': 2562180036}

In [213]:
arr_rng1.bit_generator.state = state

In [214]:
#generate large number faster than legacy regular random.random
large_array = arr_rng1.random(100)

In [215]:
arr_rng1

Generator(PCG64) at 0x1613E97FE60

In [216]:
large_array

array([0.28886324, 0.04295157, 0.9736544 , 0.5964717 , 0.79026316,
       0.91033938, 0.68815445, 0.18999147, 0.98147898, 0.28474005,
       0.62927317, 0.58103648, 0.59991227, 0.53524811, 0.9957771 ,
       0.50194608, 0.77102258, 0.49416178, 0.99767449, 0.97862192,
       0.39356804, 0.32192526, 0.86218065, 0.7993249 , 0.69143063,
       0.40851785, 0.38976513, 0.1316484 , 0.62549749, 0.08240137,
       0.27457299, 0.65611703, 0.01467603, 0.83453217, 0.07239908,
       0.52412082, 0.54655052, 0.22724696, 0.95597822, 0.34096385,
       0.50470744, 0.86738361, 0.65695295, 0.38472241, 0.09627241,
       0.95580562, 0.58956713, 0.58216289, 0.59714527, 0.14887393,
       0.56004863, 0.56316752, 0.58098818, 0.184949  , 0.70961891,
       0.07002066, 0.32486494, 0.10685547, 0.74802869, 0.50157401,
       0.4663081 , 0.07369337, 0.44209638, 0.22351108, 0.30297573,
       0.39434801, 0.70663065, 0.78636314, 0.3568361 , 0.67012985,
       0.51022312, 0.67114526, 0.33033207, 0.89841956, 0.66279

In [217]:
#Permutation & shuffle
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
arr_rng1.shuffle(arr)

In [221]:
arr

array([2, 3, 6, 8, 1, 9, 0, 5, 7, 4])

In [229]:
#Permutation returns a new array
print(arr_rng1.permutation(10))

[3 8 5 9 2 6 1 4 0 7]


In [230]:
arr_rng

Generator(PCG64) at 0x1613D88F5A0

In [231]:
#Multivariant normal 
mean = [0,0]
cov = [[1, 0.5], [0.5, 1]]
print(arr_rng1.multivariate_normal(mean, cov, size=3))

[[ 0.63771905 -0.2900345 ]
 [ 1.48670147  1.40872264]
 [-0.08373671 -0.36498162]]


In [232]:
#poisson distribution
print(arr_rng1.poisson(lam=5, size=5))

[ 7  4  4 13  4]


# Advanced

In [240]:
#Custom Generators & Parallel rng
#using different generators

In [241]:
from numpy.random import PCG64, MT19937

In [242]:
#Explicitly choose generator
rng_pcg = np.random.Generator(PCG64(seed=42))
rng_mt = np.random.Generator(MT19937(seed=42))

In [243]:
#Parallel Random Number Generation
#split generator for parallel processes
children = arr_rng.spawn(4)
print(children[0].normal())

0.330521973465665


In [244]:
print(children)

[Generator(PCG64) at 0x1613E23CF20, Generator(PCG64) at 0x1613E23D540, Generator(PCG64) at 0x1613E23C820, Generator(PCG64) at 0x1613E23C9E0]


In [245]:
print(children[2].normal())

0.0054710829827453586


In [246]:
#Cryptographic Hasing for seeds
import hashlib
seed = int(hashlib.sha256(b"secure").hexdigest(), 16) % 2**32

In [247]:
secure_rng = np.random.default_rng(seed)

In [248]:
secure_rng

Generator(PCG64) at 0x1613E23C660

In [249]:
#Create RNG 
rng = np.random.default_rng()

In [250]:
#Random float
rng.random(size=(3,3))

array([[0.4470828 , 0.22096589, 0.85296819],
       [0.15277361, 0.22615633, 0.57208062],
       [0.42615224, 0.75718114, 0.72642706]])

In [251]:
#Random int using default_rng
rng.integers(0, 50, size=(2,2))

array([[28, 22],
       [36, 11]], dtype=int64)

In [252]:
#Normal distribution
rng.normal(0, 1, size=10)

array([-0.27166562,  1.00934232,  0.54976385,  0.96261826,  0.857156  ,
        0.65217438,  0.69741764,  0.02301974,  1.84485674, -0.274626  ])

In [253]:
#shuffle
rng.shuffle(arr)

In [254]:
#Choice 
rng.choice(['a', 'b', 'c'], size=3)

array(['a', 'c', 'a'], dtype='<U1')

In [255]:
#reproduce 
rng = np.random.default_rng(seed=42)

In [263]:
rng.integers(low=3, high=5, size=(2,2))

array([[4, 4],
       [4, 4]], dtype=int64)

In [264]:
#Prallel RNG
children =rng.spawn(4)

In [269]:
for i in children:
    print(i.normal())

0.6055761737634663
0.6062894401319061
1.4059989799365469
1.460115100190716


# Numpy Random intermediate/advanced 

In [270]:
import numpy as np

In [275]:
#generate random float number between 0 and 
myfloat = np.random.random()
myfloat

0.09743637634061297

In [284]:
#Generate a matrix float between 0 and 1
mymatrix = np.random.random(size=(3,3))
mymatrix

array([[0.93689855, 0.69548469, 0.94517177],
       [0.18724345, 0.52274706, 0.9182177 ],
       [0.82379343, 0.83432555, 0.3312563 ]])

In [287]:
#Generate a matrix float between 0 and 1
mymatrix3d = np.random.random(size=(3,3,3), dtype='float64')
mymatrix3d

TypeError: random() got an unexpected keyword argument 'dtype'

In [286]:
myarray004(mymatrix3d)

Shape:  (3, 3, 3)
ndim:  3
Size:  27
DType:  float64


##### Random integers

In [306]:
myint = np.random.randint(1, 10)
myint

4

In [297]:
myintarr = np.random.randint(1, 50, size=5)
myintarr

array([ 1, 26, 48, 17, 40])

In [310]:
#how do you make 2d int arrays
myintarr2d = np.random.randint(1, 50, size=(2,2))
myintarr2d

array([[ 7, 26],
       [35, 16]])

In [312]:
myintarr2d = np.random.randint(low=1, high=50, size=(2,2))
myintarr2d

array([[41, 34],
       [48,  4]])

In [313]:
myintarr2d = np.random.randint(1, 50, (2,2))
myintarr2d

array([[40,  3],
       [ 7, 11]])

#### Simple Distributions

In [316]:
#normal distribution
np.random.normal(loc=0, scale=1, size=(2,2,5))

array([[[-1.285711  ,  0.05915552, -0.37683563,  1.68959909,
         -0.78372096],
        [-1.19049529, -0.49064187,  0.57639999, -1.35405472,
         -1.54021072]],

       [[-0.21484939,  0.10854928,  0.77765189, -1.70447952,
         -0.48459409],
        [-1.75031936,  0.12181695,  0.82912263,  0.38396671,
          0.08309305]]])

In [317]:
#uniform distribution
np.random.uniform(low=0, high=10, size=(2,2))

array([[7.44302823, 4.19072937],
       [2.59473688, 4.56801898]])

In [318]:
np.random.uniform(0, 10, (2,2))

array([[3.01577622, 1.43384692],
       [3.77341498, 8.61639381]])

#### Seeding

In [319]:
np.random.seed(42)

In [322]:
print(np.random.random())

0.7319939418114051


In [323]:
#Common probability Distributions
#Binomial distributions
print(np.random.binomial(n=10, p=0.5, size=(5,5)))

[[5 3 3 3 7]
 [5 6 2 8 7]
 [4 4 4 4 5]
 [5 4 5 3 4]
 [4 5 6 4 5]]


In [324]:
print(np.random.binomial(10, 0.5, (5,5)))

[[5 2 5 3 3]
 [8 8 6 4 3]
 [6 5 3 5 2]
 [7 4 6 4 5]
 [5 4 8 6 7]]


In [325]:
#Poison Distribution
print(np.random.poisson(lam=5, size=(2,10)))

[[ 5  5  3  3  6  4  6  6  1  7]
 [ 2 11  4  3  8  3  3  5  8  3]]


In [326]:
#exponentil distribution
print(np.random.exponential(scale=1.0, size=5))

[0.8937784  1.13185173 0.01672695 0.71763058 0.25682415]


In [331]:
#Sampling from Arrays:
arr = np.array([1,2,3,4,5])
#Random choice
print(np.random.choice(arr, size=3))

[4 2 1]


In [338]:
#with probabilities
print(np.random.choice(arr, size=3, p=[0.1, 0.1, 0.3, 0.4, 0.1]))

[3 5 5]


In [339]:
#Shuffling and permutations

In [343]:
arr = np.arange(10)
print(arr)
#shuffle in place
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[2 9 7 8 6 3 0 5 4 1]


In [344]:
#Generate permutation:
np.random.permutation(10)

array([7, 5, 1, 4, 8, 6, 0, 9, 3, 2])

In [345]:
#multivariate normal
mean =[0,0]
cov = [[1, 0.5], [0.5, 1]]
print(np.random.multivariate_normal(mean, cov, 5))

[[-0.35120579 -0.70010698]
 [ 0.44719137 -1.49703822]
 [-0.31664478 -0.26601497]
 [ 0.42595194 -0.04930541]
 [ 0.93449337  0.12097228]]


In [346]:
#Advanced
#RNG: Random Number generators
from numpy.random import Generator, PCG64
#using the newere generator
rng = Generator(PCG64())
print(rng.standard_normal(5))

[-0.49318966 -1.99197138 -0.08840309 -0.51940196 -1.91361653]


# Section 5 Numpy Array indexing and slicing

#### Numpy Basic Indexing 1D, 2D, and nD arrays

In [347]:
import numpy as np
arr_1d = np.array([10, 20, 30, 40, 50])

In [348]:
arr_1d

array([10, 20, 30, 40, 50])

In [349]:
myarray004(arr_1d)

Shape:  (5,)
ndim:  1
Size:  5
DType:  int32


In [350]:
arr_1d[0]

10

In [351]:
arr_1d[4]

50

In [352]:
arr_1d[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [353]:
arr_1d[-1]

50

In [356]:
for i in range(len(arr_1d)):
    print(arr_1d[i])

10
20
30
40
50


In [357]:
for i in range(len(arr_1d)):
    print(arr_1d[-i])

10
50
40
30
20


In [363]:
for i in range(len(arr_1d)):
    print(arr_1d[-(i + 1)])

50
40
30
20
10


In [364]:
#Slicing 
mylist = [1,2,3,4,5]
mylist[0:3]

[1, 2, 3]

In [365]:
arr_1d[0:3]

array([10, 20, 30])

In [366]:
arr_1d

array([10, 20, 30, 40, 50])

In [369]:
arr_1d[0:15:2]

array([10, 30, 50])

In [371]:
arr_1d[0:4:-1]

array([], dtype=int32)

In [372]:
arr_1d

array([10, 20, 30, 40, 50])

In [373]:
mylist

[1, 2, 3, 4, 5]

In [374]:
mylist[::-1]

[5, 4, 3, 2, 1]

In [375]:
arr_1d[::-1]

array([50, 40, 30, 20, 10])

In [379]:
arr_1d[5:1:-1]

array([50, 40, 30])

In [383]:
arr_1d[-1::-1]

array([50, 40, 30, 20, 10])

In [384]:
arr_1d[::2]

array([10, 30, 50])

In [387]:
arr_1d[-1::1]

array([50])

#### 2D arrays

In [389]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [390]:
# indexing with rows and columns
rows = 1
cols = 1

In [391]:
arr_2d[rows, cols]

5

In [398]:
arr_2d[ 1:3, 1:3]

array([[5, 6],
       [8, 9]])

arr_2d[:, :]

In [401]:
arr_2d[::-1, ::1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [402]:
arr_2d[::2, ::2]

array([[1, 3],
       [7, 9]])

#### 3D Arrays slicing

In [407]:
my3d = np.arange(0, 27).reshape(3, 3,3)

In [408]:
myarray004(my3d)

Shape:  (3, 3, 3)
ndim:  3
Size:  27
DType:  int32


In [409]:
my3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [410]:
dim1 = 2
dim2 = 2
dim3 = 2

In [412]:
my3d[dim1, dim2, dim3]

26

In [413]:
my3d[0,0,0]

0

In [415]:
my3d[2,2,2]

26

In [416]:
dim1 = 1
dim2 = 1
dim3 = 1
my3d[dim1, dim2, dim3]

13

In [425]:
rows = 0:15

SyntaxError: invalid syntax (1618403663.py, line 1)

In [434]:
my3d[3:0:-1, 3:0:-1, 3:0:-1]

array([[[26, 25],
        [23, 22]],

       [[17, 16],
        [14, 13]]])

In [435]:
my3d[3::-1, 3::-1, 3::-1]

array([[[26, 25, 24],
        [23, 22, 21],
        [20, 19, 18]],

       [[17, 16, 15],
        [14, 13, 12],
        [11, 10,  9]],

       [[ 8,  7,  6],
        [ 5,  4,  3],
        [ 2,  1,  0]]])

In [436]:
my3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [441]:
my3d[::-1, ::-1, ::-1]

array([[[26, 25, 24],
        [23, 22, 21],
        [20, 19, 18]],

       [[17, 16, 15],
        [14, 13, 12],
        [11, 10,  9]],

       [[ 8,  7,  6],
        [ 5,  4,  3],
        [ 2,  1,  0]]])

In [447]:
my3d[-1::-1, -1::-1, -1::-1]

array([[[26, 25, 24],
        [23, 22, 21],
        [20, 19, 18]],

       [[17, 16, 15],
        [14, 13, 12],
        [11, 10,  9]],

       [[ 8,  7,  6],
        [ 5,  4,  3],
        [ 2,  1,  0]]])