# Section 06 01

#### Numpy Array Arithmetic Operations (+, -, *, /, //, %, **)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
l1 = [1,2,3]
l2 = [4,5,6]

In [4]:
t1 = (1,2,3)
t2 = (4,5,6)

In [5]:
set1 = {1,2,3}
set2 = {4,5,6}

In [6]:
dict1 = {'a':1, 'b':2, 'c':3}
dict2 = {'a':1, 'b':2, 'c':3}

In [7]:
a + b

array([5, 7, 9])

In [8]:
a * b

array([ 4, 10, 18])

In [9]:
def ops1(a, b):
    print(a + b)
    print(a - b)
    print(a * b)
    print(a / b)
    print(a // b)
    print(a  % b)
    print(a ** b)

In [10]:
ops1(a, b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[  1  32 729]


In [13]:
def ops2(a, b):
    print(f"{a} + {b} = {a + b}")
    print(f"{a} - {b} = {a - b}")
    print(f"{a} * {b} = {a * b}")
    print(f"{a} / {b} = {a / b}")
    print(f"{a} // {b} = {a // b}")
    print(f"{a} % {b} = {a % b}")
    print(f"{a} ** {b} = {a ** b}")
    #+, -, *, /, //, %, **

In [14]:
ops2(a, b)

[1 2 3] + [4 5 6] = [5 7 9]
[1 2 3] - [4 5 6] = [-3 -3 -3]
[1 2 3] * [4 5 6] = [ 4 10 18]
[1 2 3] / [4 5 6] = [0.25 0.4  0.5 ]
[1 2 3] // [4 5 6] = [0 0 0]
[1 2 3] % [4 5 6] = [1 2 3]
[1 2 3] ** [4 5 6] = [  1  32 729]


In [15]:
3*3*3*3*3*3

729

In [16]:
ops1(l1, l2)

[1, 2, 3, 4, 5, 6]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [17]:
l1 + l2

[1, 2, 3, 4, 5, 6]

In [18]:
l1 - l2

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [19]:
l1 * l2

TypeError: can't multiply sequence by non-int of type 'list'

In [20]:
l1 % l2

TypeError: unsupported operand type(s) for %: 'list' and 'list'

In [21]:
ops1(t1, t2)

(1, 2, 3, 4, 5, 6)


TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

In [22]:
t1 + t2

(1, 2, 3, 4, 5, 6)

In [23]:
t1 - t2

TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

In [24]:
set1 + set2

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [25]:
dict1 + dict2

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [26]:
ops1(dict1, dict2)

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [27]:
ops2(dict2, dict1)

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [28]:
ops1(l1, l2)

[1, 2, 3, 4, 5, 6]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [29]:
ops2(a,b)

[1 2 3] + [4 5 6] = [5 7 9]
[1 2 3] - [4 5 6] = [-3 -3 -3]
[1 2 3] * [4 5 6] = [ 4 10 18]
[1 2 3] / [4 5 6] = [0.25 0.4  0.5 ]
[1 2 3] // [4 5 6] = [0 0 0]
[1 2 3] % [4 5 6] = [1 2 3]
[1 2 3] ** [4 5 6] = [  1  32 729]


In [35]:
def ops2(a, b):
    print(f"{a} + {b} = {a + b} ")
    print(f"{a} - {b} = {a - b}  ")
    print(f"{a} * {b} = {a * b}   ")
    print(f"{a} / {b} = {a / b}  ")
    print(f"{a} // {b} = {a // b}   ")
    print(f"{a} % {b} = {a % b}    ")
    print(f"{a} ** {b} = {a ** b}  ")
    #+, -, *, /, //, %, **

In [33]:
ops2(a,b)

[1 2 3] + [4 5 6] = [5 7 9] # 1 + 4, 2 + 5, 3 + 6 
[1 2 3] - [4 5 6] = [-3 -3 -3]
[1 2 3] * [4 5 6] = [ 4 10 18]
[1 2 3] / [4 5 6] = [0.25 0.4  0.5 ]
[1 2 3] // [4 5 6] = [0 0 0]
[1 2 3] % [4 5 6] = [1 2 3]
[1 2 3] ** [4 5 6] = [  1  32 729]


In [36]:
def ops3(a, b):
    print(f"{a} + {b} = {a + b} # {a[0]} + {b[0]}, {a[1]} + {b[1]}, {a[2]} + {b[2]} ")
    print(f"{a} - {b} = {a - b} # {a[0]} - {b[0]}, {a[1]} - {b[1]}, {a[2]} - {b[2]} ")
    print(f"{a} * {b} = {a * b} # {a[0]} * {b[0]}, {a[1]} * {b[1]}, {a[2]} * {b[2]} ")
    print(f"{a} / {b} = {a / b} # {a[0]} / {b[0]}, {a[1]} / {b[1]}, {a[2]} / {b[2]} ")
    print(f"{a} // {b} = {a // b} # {a[0]} // {b[0]}, {a[1]} //{b[1]}, {a[2]} // {b[2]} ")
    print(f"{a} % {b} = {a % b}  # {a[0]} % {b[0]}, {a[1]} % {b[1]}, {a[2]}  % {b[2]} ")
    print(f"{a} ** {b} = {a ** b}  # {a[0]} ** {b[0]}, {a[1]} ** {b[1]}, {a[2]} ** {b[2]}")

In [37]:
ops3(a,b)

[1 2 3] + [4 5 6] = [5 7 9] # 1 + 4, 2 + 5, 3 + 6 
[1 2 3] - [4 5 6] = [-3 -3 -3] # 1 - 4, 2 - 5, 3 - 6 
[1 2 3] * [4 5 6] = [ 4 10 18] # 1 * 4, 2 * 5, 3 * 6 
[1 2 3] / [4 5 6] = [0.25 0.4  0.5 ] # 1 / 4, 2 / 5, 3 / 6 
[1 2 3] // [4 5 6] = [0 0 0] # 1 // 4, 2 //5, 3 // 6 
[1 2 3] % [4 5 6] = [1 2 3]  # 1 % 4, 2 % 5, 3  % 6 
[1 2 3] ** [4 5 6] = [  1  32 729]  # 1 ** 4, 2 ** 5, 3 ** 6


In [38]:
ops3(l1, l2)

[1, 2, 3] + [4, 5, 6] = [1, 2, 3, 4, 5, 6] # 1 + 4, 2 + 5, 3 + 6 


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [39]:
ops3(set1, set2)

TypeError: unsupported operand type(s) for +: 'set' and 'set'

### Scalar operations

In [40]:
3 * a

array([3, 6, 9])

In [41]:
ops1(3, a)

[4 5 6]
[2 1 0]
[3 6 9]
[3.  1.5 1. ]
[3 1 1]
[0 1 0]
[ 3  9 27]


In [42]:
ops2(3,a)

3 + [1 2 3] = [4 5 6] 
3 - [1 2 3] = [2 1 0]  
3 * [1 2 3] = [3 6 9]   
3 / [1 2 3] = [3.  1.5 1. ]  
3 // [1 2 3] = [3 1 1]   
3 % [1 2 3] = [0 1 0]    
3 ** [1 2 3] = [ 3  9 27]  


In [43]:
ops3(3,a)

TypeError: 'int' object is not subscriptable

In [44]:
matrix = np.array([[1,2,3], [4,5,6]])

In [45]:
ops1(a, matrix)

[[2 4 6]
 [5 7 9]]
[[ 0  0  0]
 [-3 -3 -3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]
[[1 1 1]
 [0 0 0]]
[[0 0 0]
 [1 2 3]]
[[  1   4  27]
 [  1  32 729]]


In [46]:
ops1(matrix, a)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]
[[1 1 1]
 [4 2 2]]
[[0 0 0]
 [0 1 0]]
[[  1   4  27]
 [  4  25 216]]


In [47]:
ops2(matrix, a)

[[1 2 3]
 [4 5 6]] + [1 2 3] = [[2 4 6]
 [5 7 9]] 
[[1 2 3]
 [4 5 6]] - [1 2 3] = [[0 0 0]
 [3 3 3]]  
[[1 2 3]
 [4 5 6]] * [1 2 3] = [[ 1  4  9]
 [ 4 10 18]]   
[[1 2 3]
 [4 5 6]] / [1 2 3] = [[1.  1.  1. ]
 [4.  2.5 2. ]]  
[[1 2 3]
 [4 5 6]] // [1 2 3] = [[1 1 1]
 [4 2 2]]   
[[1 2 3]
 [4 5 6]] % [1 2 3] = [[0 0 0]
 [0 1 0]]    
[[1 2 3]
 [4 5 6]] ** [1 2 3] = [[  1   4  27]
 [  4  25 216]]  


In [50]:
ops3(b, matrix)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [52]:
ops2(matrix, a)

[[1 2 3]
 [4 5 6]] + [1 2 3] = [[2 4 6]
 [5 7 9]] 
[[1 2 3]
 [4 5 6]] - [1 2 3] = [[0 0 0]
 [3 3 3]]  
[[1 2 3]
 [4 5 6]] * [1 2 3] = [[ 1  4  9]
 [ 4 10 18]]   
[[1 2 3]
 [4 5 6]] / [1 2 3] = [[1.  1.  1. ]
 [4.  2.5 2. ]]  
[[1 2 3]
 [4 5 6]] // [1 2 3] = [[1 1 1]
 [4 2 2]]   
[[1 2 3]
 [4 5 6]] % [1 2 3] = [[0 0 0]
 [0 1 0]]    
[[1 2 3]
 [4 5 6]] ** [1 2 3] = [[  1   4  27]
 [  4  25 216]]  


#### Numpy math functions

In [53]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [54]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [55]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [56]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654])

In [57]:
np.cot(a)

AttributeError: module 'numpy' has no attribute 'cot'

In [58]:
np.tanh(a)

array([0.76159416, 0.96402758, 0.99505475])

In [59]:
np.sinh(a)

array([ 1.17520119,  3.62686041, 10.01787493])

In [60]:
np.cosh(a)

array([ 1.54308063,  3.76219569, 10.067662  ])

In [61]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [62]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [63]:
a * b

array([ 4, 10, 18])

In [64]:
a @ b

32

In [67]:
a3 = np.arange(9).reshape(3,3)

In [68]:
a3  * a3

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [69]:
a3 @ a3 

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [70]:
np.matmul(a3, a3)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [73]:
def ops4(a, b):
    print(f"{a} + {b} = {a + b} # {a[0]} + {b[0]}, {a[1]} + {b[1]}, {a[2]} + {b[2]} ")
    print(f"{a} - {b} = {a - b}  # {a[0]} - {b[0]}, {a[1]} - {b[1]}, {a[2]} - {b[2]} ")
    print(f"{a} * {b} = {a * b}  # {a[0]} * {b[0]}, {a[1]} * {b[1]}, {a[2]} * {b[2]} ")
    print(f"{a} / {b} = {a / b}  # {a[0]} / {b[0]}, {a[1]} / {b[1]}, {a[2]} / {b[2]} " )
    print(f"{a} // {b} = {a // b}  # {a[0]} // {b[0]}, {a[1]} //{b[1]}, {a[2]} // {b[2]} ")
    print(f"{a} % {b} = {a % b}  # {a[0]} % {b[0]}, {a[1]} % {b[1]}, {a[2]}  % {b[2]} ")
    print(f"{a} ** {b} = {a ** b}  # {a[0]} ** {b[0]}, {a[1]} ** {b[1]}, {a[2]} ** {b[2]} ")
    print(f"{a} @ {b} = {a @ b}")
    print("Alternativley np.matmul(a,b) = ", np.matmul(a,b))

In [76]:
ops4(a, b)

[1 2 3] + [4 5 6] = [5 7 9] # 1 + 4, 2 + 5, 3 + 6 
[1 2 3] - [4 5 6] = [-3 -3 -3]  # 1 - 4, 2 - 5, 3 - 6 
[1 2 3] * [4 5 6] = [ 4 10 18]  # 1 * 4, 2 * 5, 3 * 6 
[1 2 3] / [4 5 6] = [0.25 0.4  0.5 ]  # 1 / 4, 2 / 5, 3 / 6 
[1 2 3] // [4 5 6] = [0 0 0]  # 1 // 4, 2 //5, 3 // 6 
[1 2 3] % [4 5 6] = [1 2 3]  # 1 % 4, 2 % 5, 3  % 6 
[1 2 3] ** [4 5 6] = [  1  32 729]  # 1 ** 4, 2 ** 5, 3 ** 6 
[1 2 3] @ [4 5 6] = 32
Alternativley np.matmul(a,b) =  32


In [77]:
ops4(matrix, matrix)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [78]:
ops2(matrix, matrix)

[[1 2 3]
 [4 5 6]] + [[1 2 3]
 [4 5 6]] = [[ 2  4  6]
 [ 8 10 12]] 
[[1 2 3]
 [4 5 6]] - [[1 2 3]
 [4 5 6]] = [[0 0 0]
 [0 0 0]]  
[[1 2 3]
 [4 5 6]] * [[1 2 3]
 [4 5 6]] = [[ 1  4  9]
 [16 25 36]]   
[[1 2 3]
 [4 5 6]] / [[1 2 3]
 [4 5 6]] = [[1. 1. 1.]
 [1. 1. 1.]]  
[[1 2 3]
 [4 5 6]] // [[1 2 3]
 [4 5 6]] = [[1 1 1]
 [1 1 1]]   
[[1 2 3]
 [4 5 6]] % [[1 2 3]
 [4 5 6]] = [[0 0 0]
 [0 0 0]]    
[[1 2 3]
 [4 5 6]] ** [[1 2 3]
 [4 5 6]] = [[    1     4    27]
 [  256  3125 46656]]  


#### Aggregations Operations


In [79]:
#sum, mean, max, std, prod"

In [80]:
def agg1(a):
    print(np.sum(a))
    print(np.mean(a))
    print(np.max(a))
    print(np.std(a))
    print(np.prod(a))

In [81]:
agg1(a)

6
2.0
3
0.816496580927726
6


In [84]:
def agg2(a):
    print(f"np.sum({a}) = {np.sum(a)}")
    print(f"np.min({a}) = {np.min(a)}")
    print(f"np.mean({a}) = {np.mean(a)}")
    print(f"np.max({a}) = {np.max(a)}")
    print(f"np.std({a}) = {np.std(a)}")
    print(f"np.prod({a}) = {np.prod(a)}")
    

In [85]:
agg2(a)

np.sum([1 2 3]) = 6
np.min([1 2 3]) = 1
np.mean([1 2 3]) = 2.0
np.max([1 2 3]) = 3
np.std([1 2 3]) = 0.816496580927726
np.prod([1 2 3]) = 6
