# Linear Algebra solutions

### Determinants

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1, 100, (3,3))

In [3]:
arr1 

array([[75, 13, 36],
       [54,  6, 73],
       [31, 34, 85]])

In [5]:
Det1 = np.linalg.det(arr1)

In [6]:
Det1

-118750.9999999999

In [7]:
#-118751 

In [9]:
arr2 = np.array([[1,2], [3,4]])

In [11]:
det2 = np.linalg.det(arr2)
print(det2)

-2.0000000000000004


In [12]:
arr3 = np.array([[3,4], [1,2]])

In [13]:
det3 = np.linalg.det(arr3)
print(det3)

2.0000000000000004


In [14]:
arr4 = np.array([[1,4], [3,2]])

In [15]:
det4 = np.linalg.det(arr4)
print(det4)

-10.000000000000002


In [16]:
arr5 = np.array([[1,3], [2,4]])

In [17]:
arr5

array([[1, 3],
       [2, 4]])

In [18]:
det5 = np.linalg.det(arr5)
print(det5)

-2.0


In [20]:
# 3D matrices

In [22]:
arr3d = np.arange(9).reshape(3,3)

In [23]:
arr3d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
det3d = np.linalg.det(arr3d)
print(det3d)

0.0


In [25]:
arr3d_A = np.array([
       [3, 4, 5],
    [0, 1, 2],
       [6, 7, 8]])

In [26]:
arr3d_A

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [28]:
det3d_A = np.linalg.det(arr3d_A)
print(det3d_A)

0.0


In [29]:
detrandom = np.random.randint(1, 25, (3,3))
print(detrandom)

[[24  1 17]
 [15 20 15]
 [19 24  1]]


In [30]:
detr = np.linalg.det(detrandom)
print(detr)

-8230.00000000001


# Section 08 02 Inverse function

In [31]:
import numpy as np

A = np.array([
    [4,7],
    [2,6]
])

A_inv = np.linalg.inv(A)
print(A_inv)

In [33]:
A1 = A * A_inv
print(A1)

[[ 2.4 -4.9]
 [-0.4  2.4]]


In [34]:
A2 = A @ A_inv

In [35]:
print(A2)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [36]:
identity = np.round(A2)

In [37]:
identity

array([[ 1., -0.],
       [ 0.,  1.]])

In [39]:
# Section 08 04 Eigva Eigvec

In [40]:
import numpy as np

In [58]:
A = np.array([[3,1],
              [1,3]])

evu, evec = np.linalg.eig(A)
print("Eigenvalues: ", evu)
print("Eigenvectors: ", evec)

Eigenvalues:  [4. 2.]
Eigenvectors:  [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [59]:
np.round((A @ evec), 3)

array([[ 2.828, -1.414],
       [ 2.828,  1.414]])

In [60]:
np.round((evec * evu), 3)

array([[ 2.828, -1.414],
       [ 2.828,  1.414]])

In [61]:
np.round((A @ evec), 3) == np.round((evec * evu), 3)

array([[ True,  True],
       [ True,  True]])

In [67]:
A3 = np.array([[1,3,1],
              [3,1,3],
              [4,5,6]])
print(A3.ndim)
evu3, evec3 = np.linalg.eig(A3)
print("Eigenvalues: ", evu3)
print("Eigenvectors: ", evec3)

2
Eigenvalues:  [ 9.41296751  0.77638578 -2.18935329]
Eigenvectors:  [[-0.24832196 -0.68836545  0.65676293]
 [-0.4027079  -0.1826847  -0.74237146]
 [-0.88100088  0.70198241  0.13246535]]


In [68]:
np.round((A3 @ evec3), 3) == np.round((evec3 * evu3), 3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])