# Section 07 01

#### Section 07 01 Reshape arrays with reshape(), flatten(), and ravel()

In [1]:
import numpy as np

In [2]:
arr = np.arange(12)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [5]:
arr.ndim

1

In [6]:
arr.shape

(12,)

In [7]:
print(arr.shape)

(12,)


In [8]:
reshape = arr.reshape(3,4)

In [9]:
reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
arr[0] = 100

In [11]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [12]:
reshape

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [13]:
reshape[0][0] = 0

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
# Reshape with different orders:
resC = arr.reshape(3,4, order='C')
resF = arr.reshape(3,4, order = 'F')

In [17]:
resC

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
resF

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [19]:
resF[0][0] = 33

In [20]:
resF

array([[33,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [21]:
resC

array([[33,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
arr

array([33,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
arr

array([33,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
res2 = arr.reshape(2, -1)

In [25]:
res2

array([[33,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
arr2 = np.arange(7)
arr2

array([0, 1, 2, 3, 4, 5, 6])

In [30]:
res3 = arr2.reshape(2,-1)

ValueError: cannot reshape array of size 7 into shape (2,newaxis)

In [33]:
res3 = arr.reshape(3, 4)

In [34]:
res3

array([[33,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
res4 = arr.reshape(2,2,-1)

In [36]:
res4

array([[[33,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [37]:
res5 = arr.reshape(2,2,3)

In [38]:
res5

array([[[33,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [39]:
res5 == res4

array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [40]:
res5 is res4

False

In [41]:
res5[0][0] = 55

In [42]:
res5

array([[[55, 55, 55],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [43]:
res4

array([[[55, 55, 55],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [44]:
res4

array([[[55, 55, 55],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [46]:
res6 = res4.flatten()

In [47]:
res6

array([55, 55, 55,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
res6[0] = 0
res6[1] = 1
res6[2] = 2

In [49]:
res6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
res5

array([[[55, 55, 55],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [51]:
res4

array([[[55, 55, 55],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [52]:
res6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
res7 = res6.reshape(3,4)

In [54]:
res7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
res7[0][0] = 44

In [56]:
res7

array([[44,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
res6

array([44,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
res8 = res6.flatten().reshape(3,4)

In [60]:
res8

array([[44,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
res6

array([44,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
res8[0][0] = 11

In [63]:
res8

array([[11,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
res6

array([44,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
id(res6)

1672665411152

In [66]:
id(res8)

1672674418704

In [67]:
id(res7)

1672674417744

In [68]:
id(res6)

1672665411152

In [69]:
id(res5)

1672674417552

In [70]:
id(res4)

1672674415440

In [71]:
id(res3)

1672674416784

In [72]:
#Create a 2d Array 
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [73]:
flat1 = arr_2d.flatten()

In [74]:
flat1

array([1, 2, 3, 4, 5, 6])

In [75]:
flat1[0] = 100

In [76]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr_2d[0][0] = 999

In [78]:
arr_2d

array([[999,   2,   3],
       [  4,   5,   6]])

In [79]:
flat1

array([100,   2,   3,   4,   5,   6])

# ravel()

In [80]:
#ravel like flatten converts multi-d arrays to 1 D array but returns a view

In [81]:
arr_2d

array([[999,   2,   3],
       [  4,   5,   6]])

In [82]:
arr_2d[0][0] = 1

In [83]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
raveled = arr_2d.ravel()

In [85]:
raveled

array([1, 2, 3, 4, 5, 6])

In [86]:
raveled[0] = 49494

In [87]:
arr_2d

array([[49494,     2,     3],
       [    4,     5,     6]])

In [88]:
# Modifying raveled affects original when it's a view

In [89]:
print("Row-major ravel:", arr_2d.ravel('C'))
print("Column-major ravel:", arr_2d.ravel('F'))

Row-major ravel: [49494     2     3     4     5     6]
Column-major ravel: [49494     4     2     5     3     6]


In [90]:
#Memory considerations
# 
# Check if array is C-contiguous
print("Is C-contiguous:", arr_2d.flags['C_CONTIGUOUS'])

# Non-contiguous example
arr_non_contig = arr_2d[:, ::2]  # Take every other column
print("Is non-contiguous array C-contiguous:", arr_non_contig.flags['C_CONTIGUOUS'])

Is C-contiguous: True
Is non-contiguous array C-contiguous: False


# Section 07 02 Swapping and Transposing

### Transposing

In [91]:
import numpy as np

In [92]:
arr = np.array([[1,2,3], [4,5,6]]) 

In [93]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [96]:
trans = arr.T   

In [97]:
trans

array([[1, 4],
       [2, 5],
       [3, 6]])

In [98]:
trans.shape

(3, 2)

In [99]:
arr.shape

(2, 3)

In [100]:
transposed = np.transpose(arr)

In [101]:
transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [102]:
#exatly the same as .T 

In [104]:
transposed[0][0] = 100

In [105]:
transposed

array([[100,   4],
       [  2,   5],
       [  3,   6]])

In [106]:
trans

array([[100,   4],
       [  2,   5],
       [  3,   6]])

In [107]:
arr

array([[100,   2,   3],
       [  4,   5,   6]])

In [113]:
arr_md = np.random.randint(1, 100, (3,4,5))

In [114]:
arr_md

array([[[52, 49, 13, 43, 56],
        [45, 36, 18, 83, 19],
        [96, 94, 61, 69, 25],
        [86, 20, 92, 55, 10]],

       [[92, 43, 46,  9, 35],
        [27,  4, 99, 82, 44],
        [23, 65, 39, 11, 94],
        [20, 13, 58, 94, 99]],

       [[96, 64, 86, 47, 55],
        [55, 29, 81, 58, 26],
        [49, 95,  8,  8, 16],
        [39, 85, 54,  3, 44]]])

In [115]:
tr_md = arr_md.T

In [116]:
tr_md

array([[[52, 92, 96],
        [45, 27, 55],
        [96, 23, 49],
        [86, 20, 39]],

       [[49, 43, 64],
        [36,  4, 29],
        [94, 65, 95],
        [20, 13, 85]],

       [[13, 46, 86],
        [18, 99, 81],
        [61, 39,  8],
        [92, 58, 54]],

       [[43,  9, 47],
        [83, 82, 58],
        [69, 11,  8],
        [55, 94,  3]],

       [[56, 35, 55],
        [19, 44, 26],
        [25, 94, 16],
        [10, 99, 44]]])

In [117]:
arr = np.random.rand(2,3,4)

In [118]:
arr

array([[[0.0103938 , 0.00418215, 0.45621538, 0.68316065],
        [0.95584031, 0.66599149, 0.51783909, 0.3014665 ],
        [0.1968628 , 0.45037199, 0.36166954, 0.76053469]],

       [[0.19787094, 0.44413176, 0.73379152, 0.27023447],
        [0.50353636, 0.71589603, 0.5077129 , 0.72697201],
        [0.749101  , 0.34237169, 0.40496127, 0.61601537]]])

In [119]:
custom_tra = np.transpose(arr, (1,2,0))

In [120]:
custom_tra

array([[[0.0103938 , 0.19787094],
        [0.00418215, 0.44413176],
        [0.45621538, 0.73379152],
        [0.68316065, 0.27023447]],

       [[0.95584031, 0.50353636],
        [0.66599149, 0.71589603],
        [0.51783909, 0.5077129 ],
        [0.3014665 , 0.72697201]],

       [[0.1968628 , 0.749101  ],
        [0.45037199, 0.34237169],
        [0.36166954, 0.40496127],
        [0.76053469, 0.61601537]]])

In [134]:
arr = np.arange(24).reshape(2,3,4)

In [136]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [137]:
cu_tr = np.transpose(arr, (1,2,0))

In [138]:
cu_tr

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [139]:
arr.ndim

3

In [142]:
arr_2d.ndim

2

In [144]:
arr_2d.transpose()

array([[49494,     4],
       [    2,     5],
       [    3,     6]])

### Numpy Swapping

In [145]:
import numpy as np

In [147]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [148]:
arr[1], arr[3] = arr[3], arr[1]
arr

array([10, 40, 30, 20])

In [149]:
arr = np.array([[1,2,3], 
                [4,5,6],
                [7,8,9]])
#Swap row 0 and 2
arr[[0,2]] = arr[[2,0]]

In [150]:
arr

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [151]:
#Swap columns

In [152]:
arr[:, [1,2]] = arr[:, [2,1]]

In [153]:
arr

array([[7, 9, 8],
       [4, 6, 5],
       [1, 3, 2]])

In [156]:
#Swap axes
arr = np.arange(8).reshape(2,2,2) 
print(arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [157]:
swapped = np.swapaxes(arr, 0, 1)
print(swapped)

[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


# Section 07 03 Concatenation

#### Basic Concatenation (np.concatenate)

In [158]:
#1.1 Joining 1D Arrays

In [159]:
import numpy as np

In [160]:
a = np.array([1,2,3])
b = np.array([4,5,6])
#join as is
result = np.concatenate((a,b))
print(result)


[1 2 3 4 5 6]


In [161]:
result = np.concatenate((a,b), axis=0)
print(result)

[1 2 3 4 5 6]


In [162]:
result = np.concatenate((a,b), axis=1)
print(result)

AxisError: axis 1 is out of bounds for array of dimension 1

In [163]:
result.ndim

1

In [164]:
a.ndim

1

In [166]:
#Joining 2D arrays
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6]])

#Vertical stacking (axis=0)  similar to inserting a row in a table
v_stack = np.concatenate((arr1, arr2), axis=0)
print(v_stack)

[[1 2]
 [3 4]
 [5 6]]


In [167]:
v_stack2 = np.concatenate((arr1, arr2), axis=1)
print(v_stack2)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [176]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
h_stack2 = np.concatenate((arr1, arr2), axis=1)
print(h_stack2)

[[1 2 5 6]
 [3 4 7 8]]


In [177]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8], [9, 10]])
v_stack2 = np.concatenate((arr1, arr2), axis=0)
print(v_stack2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [179]:
#Horizontal stacking (axis = 1)
arr3 = np.array([[7], [8]])
h_stack = np.concatenate((arr1, arr3), axis=1)
print(h_stack)

[[1 2 7]
 [3 4 8]]


In [180]:
#Axis 0 means appending rows to the table (spreadsheet)
#Axis 1 means appending columns to the table (spreadsheet)

In [181]:
#Horizontal Stacking (axis=1)
arr3 = np.array([[7,9,10], [8,10,10]])
h_stack = np.concatenate((arr1, arr3), axis = 1)
print(h_stack)

[[ 1  2  7  9 10]
 [ 3  4  8 10 10]]


In [182]:
arr1

array([[1, 2],
       [3, 4]])

### Convenience Functions
### vstacking

In [184]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# Convert 1D to 2D and stack it vertically
result = np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


In [185]:
# hstack 

In [186]:
a = np.array([[1],[2]])
b = np.array([[3], [4]])

#stack it horizontlay
result = np.hstack((a, b))
print(result)

[[1 3]
 [2 4]]


In [188]:
# Depth-wise stacking (dstack)
#stack along a third dimension
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

result = np.dstack((a, b))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [189]:
result.ndim

3

In [190]:
a.ndim

2

In [191]:
# np.stack

In [192]:
a = np.array([1,2,3])
b = np.array([4,5,6])
#stack along a new axis (default is axis=0)
result = np.stack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


In [193]:
# stack along a second axis
result = np.stack((a, b), axis=1)
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [194]:
# Stack along 3rd Dimension
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7, 8]])
result = np.stack((a, b), axis=2)
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


# Optional
# Machine Learning

In [195]:
features1 = np.random.rand(22, 5)  # First set of features
features2 = np.random.rand(22, 3)  # Second set

# Combine features horizontally
X = np.hstack((features1, features2))
print(X.shape)  # (22, 8)

(22, 8)


In [196]:
#Time Series Data
time_points = np.arange(10)
sensor1 = np.random.rand(10)
sensor2 = np.random.rand(10)

# Create multivariate time series
time_series = np.column_stack((time_points, sensor1, sensor2))
print(time_series.shape)  # (10, 3)

(10, 3)


5. Performance Considerations
Method	         Use Case	        Memory Efficiency	Speed
concatenate	     General purpose	High	            Fast
vstack/hstack	 Si mplified syntax	Medium	            Fast
stack	         Creating new d 	Low	                Slower
dstack	         Depth-wise st   	Medium	             Fast

# Section 07 04 Splitting functions

In [197]:
import numpy as np

In [198]:
arr = np.arange(10)
print('arr: ', arr)

arr:  [0 1 2 3 4 5 6 7 8 9]


In [203]:
#splitting in two
result = np.split(arr, 2)
for i in result:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]


In [204]:
result[0]

array([0, 1, 2, 3, 4])

In [205]:
result[1]

array([5, 6, 7, 8, 9])

In [206]:
result[0][0] = 100

In [207]:
result[0]

array([100,   1,   2,   3,   4])

In [208]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [209]:
#uneven, unequal division
#split at specific indices
arr = np.arange(10)
result = np.split(arr, [2, 6])

In [210]:
for i in result:
    print(i)

[0 1]
[2 3 4 5]
[6 7 8 9]


In [212]:
#2D array splitting (Advanced)
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
#split vertically (rows)
result = np.split(arr_2d, 3, axis=0)
for i in result:
    print(i)
    print("*"*40)

[[1 2 3]]
****************************************
[[4 5 6]]
****************************************
[[7 8 9]]
****************************************


In [218]:
print(result[1])

[[4 5 6]]


In [219]:
#split horizontally (columns)
result = np.split(arr_2d, 3, axis=1)
for i in result:
    print(i)

[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


#### Convenience functions

##### hsplit

In [221]:
#Horizontal splitting
arr = np.array([[1,2,3,4], [5,6,7,8]])

#split into 2 equal columns
result = np.hsplit(arr, 2)
for i in result:
    print(i)
    print("________")

[[1 2]
 [5 6]]
________
[[3 4]
 [7 8]]
________


In [223]:
#split at specific indices
result = np.hsplit(arr, [1,3])
for i in result:
    print(i)
    print("________")

[[1]
 [5]]
________
[[2 3]
 [6 7]]
________
[[4]
 [8]]
________


In [225]:
# vsplit (vertical splittin)
result = np.split(arr, 2)
for i in result:
    print(i)
    print("________")

[[1 2 3 4]]
________
[[5 6 7 8]]
________


In [226]:
result = np.vsplit(arr, [1,3])
for i in result:
    print(i)
    print("--------")

[[1 2 3 4]]
--------
[[5 6 7 8]]
--------
[]
--------


In [227]:
#Optional 
#Depth-wise splitting dsplit()

In [228]:
arr_3d = np.arange(8).reshape(2,2,2)
print(arr_3d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [230]:
#split along depth (3rd axis)
result = np.dsplit(arr_3d, 2)
for i in result:
    print(i)

[[[0]
  [2]]

 [[4]
  [6]]]
[[[1]
  [3]]

 [[5]
  [7]]]


In [231]:
#Array positioning (np.array_split)
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [232]:
#split in 3 parts
result = np.array_split(arr, 3)
for i in result:
    print(i)

[0 1 2 3]
[4 5 6]
[7 8 9]


### Machine Learning

In [233]:
data = np.random.rand(100, 5)  # 100 samples, 5 features
train, test = np.split(data, [int(0.8*len(data))])
print(train.shape, test.shape)  # (80, 5), (20, 5)

(80, 5) (20, 5)


### Time Series 

In [234]:
time_series = np.arange(100)
windows = np.split(time_series, range(10, 100, 10))
print(len(windows))  # 10 windows (9 of size 10, last of size 10)

10
