# Section 05 02 intermediate/Advanced level indxing/slicing

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(0, 10).reshape(2,5)

In [3]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
#Boolean indexing
list1 = [1,2,3,4,5]
arr = np.array(list1)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr > 2

array([False, False,  True,  True,  True])

In [9]:
arr[0] > 2

False

In [10]:
arr[1] > 2

False

In [11]:
arr[2] > 2

True

In [13]:
list1[list1>2]

TypeError: '>' not supported between instances of 'list' and 'int'

In [19]:
newlist = []
for i in list1:
    if i > 2:
        newlist.append(True)
    else:
        newlist.append(False)

In [20]:
newlist

[False, False, True, True, True]

In [21]:
arr3 = arr>2

In [22]:
arr3

array([False, False,  True,  True,  True])

In [23]:
arr3

array([False, False,  True,  True,  True])

In [24]:
arr

array([1, 2, 3, 4, 5])

In [25]:
arr[arr3]

array([3, 4, 5])

In [29]:
arr[[False, False, True, True, True]]

array([3, 4, 5])

In [31]:
arr[arr>=2]

array([2, 3, 4, 5])

In [34]:
arr[arr< 3]

array([1, 2])

In [44]:
arr[(arr==2) | ( arr==1)]

array([1, 2])

In [50]:
arr[(arr> 1) & ( arr< 5)]

array([2, 3, 4])

In [57]:
arr1[(arr1> 1) & ( arr1< 5)]

array([2, 3, 4])

In [52]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
arr2 = arr1[(arr1> 1) & ( arr1 > 6)]
arr2

array([7, 8, 9])

In [61]:
np.ndim(arr2)

1

In [64]:
arr2d = np.array([[1,2], [3,4], [5,6]])
print(arr2d)
print(arr2d[arr2d > 3])

[[1 2]
 [3 4]
 [5 6]]
[4 5 6]


In [66]:
#Fancy indeding (integer array indexing)
arr = np.array([10, 20, 30, 40, 50])

indices = [1,3,4]  
ind1 = [False, True, False, True, True]
print(arr[indices])
print(arr[ind1])

[20 40 50]
[20 40 50]


In [68]:
#2d example
arr2d = np.array([[1,2], [3,4], [5,6]])
print(arr2d[[0, 2], [0, 1]]) 

[1 6]


In [69]:
arr2d = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
#combine slicing and fancy indexing
print(arr2d[[0,2], :]) 

[[1 2 3]
 [7 8 9]]


In [70]:
print(arr2d[:, [1,2]])

[[2 3]
 [5 6]
 [8 9]]


### Views vs Copies

In [71]:
arr = np.array([1,2,3,4,5])
view = arr[1:4]

In [72]:
view

array([2, 3, 4])

In [73]:
arr

array([1, 2, 3, 4, 5])

In [74]:
arr[0] = 99

In [75]:
view

array([2, 3, 4])

In [76]:
view[0] = 99

In [77]:
arr

array([99, 99,  3,  4,  5])

In [78]:
arr = np.array([1,2,3,4,5])
view = arr[1:4]

In [79]:
view

array([2, 3, 4])

In [80]:
arr

array([1, 2, 3, 4, 5])

In [81]:
view[0] = 99

In [82]:
view

array([99,  3,  4])

In [83]:
arr

array([ 1, 99,  3,  4,  5])

In [84]:
arr[1] = 2

In [85]:
arr

array([1, 2, 3, 4, 5])

In [86]:
view

array([2, 3, 4])

In [87]:
copy = arr[[1,3]]

In [88]:
copy

array([2, 4])

In [89]:
arr

array([1, 2, 3, 4, 5])

In [90]:
copy[0] = 99
arr

array([1, 2, 3, 4, 5])

In [91]:
arr[2] = 105

In [92]:
copy

array([99,  4])

In [97]:
arr = np.array( [1,2,3,4,5])
copy = arr[[0, 1, 2, 3, 4]]

In [98]:
arr


array([1, 2, 3, 4, 5])

In [99]:
copy

array([1, 2, 3, 4, 5])

In [100]:
arr[0] = 99

In [101]:
copy

array([1, 2, 3, 4, 5])

In [102]:
arr

array([99,  2,  3,  4,  5])

In [103]:
copy[0] = 99

In [104]:
arr

array([99,  2,  3,  4,  5])

In [105]:
arr = np.arange(1, 10)

In [106]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
condition = (arr>3) & (arr<7)
print(arr[condition])

[4 5 6]


In [109]:
#using np.where
indices = np.where(arr % 2 == 0) 
print(arr[indices])

[2 4 6 8]


In [110]:
list1

[1, 2, 3, 4, 5]

In [113]:
newlist = []
for i in list1:
    if i%2 == 1:
        newlist.append(i)


In [114]:
newlist

[1, 3, 5]

In [120]:
np.where((arr>4) & ( arr < 8))

(array([4, 5, 6], dtype=int64),)

### Masking

In [121]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
mask = arr2d > 5
print(mask)
print("*"*40)
print(arr2d[mask])

[[False False False]
 [False False  True]
 [ True  True  True]]
****************************************
[6 7 8 9]


In [124]:
np.where(arr2d>5, arr2d, -1)

array([[-1, -1, -1],
       [-1, -1,  6],
       [ 7,  8,  9]])

In [125]:
#Advanced 3D indexing Techniques
arr3d = np.random.randint(0, 10, (3,3,3))

In [126]:
arr3d

array([[[1, 8, 9],
        [2, 2, 1],
        [3, 3, 3]],

       [[8, 1, 7],
        [0, 5, 3],
        [3, 2, 7]],

       [[0, 6, 5],
        [4, 3, 3],
        [9, 7, 6]]])

In [130]:
#indexing iwth arrays
rows = np.array([0,1,2])
cols = np.array([0, 1,2])
print(arr3d[0, rows, cols])

[1 2 3]


In [131]:
#combining with broadcasting
depths = np.array([0,1,2])[:, np.newaxis, np.newaxis]
print(arr3d[depths, rows, cols])

[[[1 2 3]]

 [[8 5 7]]

 [[0 3 6]]]


# Important - urgent

# Modifying array elements

In [132]:
import numpy as np

In [133]:
arr = np.arange(1,6)

In [134]:
arr

array([1, 2, 3, 4, 5])

In [135]:
arr[0]

1

In [136]:
arr[0] = 100

In [137]:
arr

array([100,   2,   3,   4,   5])

In [138]:
#bulk modifications
arr[1:4] = [200, 300, 400]

In [139]:
arr

array([100, 200, 300, 400,   5])

In [140]:
len(arr[1:4])  == len([200, 300, 400])

True

In [143]:
arr[1:4] =  [200, 300, 400, 500]

ValueError: could not broadcast input array from shape (4,) into shape (3,)

# Important


### Boolean masking

In [146]:
arr > 100

array([False,  True,  True,  True, False])

In [147]:
arr

array([100, 200, 300, 400,   5])

In [148]:
arr[arr>100] = arr/100

ValueError: NumPy boolean array indexing assignment cannot assign 5 input values to the 3 output values where the mask is true

In [149]:
arr/100

array([1.  , 2.  , 3.  , 4.  , 0.05])

In [150]:
arr[arr>100]

array([200, 300, 400])

In [154]:
arr[arr>99] = arr[arr>99]/100

In [155]:
arr

array([1, 2, 3, 4, 5])

### where to change mask modify

In [156]:
arr = np.array([100, 200, 300, 400,   5])

In [157]:
arr

array([100, 200, 300, 400,   5])

In [158]:
arr = np.where(arr>99, arr/100, arr)

In [159]:
arr

array([1., 2., 3., 4., 5.])

In [160]:
arr = np.where((arr>4) & (arr<7), arr + 55, arr)

In [161]:
#[1, 2, 3, 4, 60]
arr

array([ 1.,  2.,  3.,  4., 60.])

In [162]:
arr[arr>4]=999

In [163]:
arr

array([  1.,   2.,   3.,   4., 999.])

In [164]:
arr = np.array([1,2,3,4,5])

In [165]:
new_arr = np.where(arr>3, 100, arr)

In [166]:
new_arr

array([  1,   2,   3, 100, 100])

In [167]:
#inplace operations
arr *= 2

In [168]:
arr

array([ 2,  4,  6,  8, 10])

In [169]:
arr += 100

In [170]:
arr

array([102, 104, 106, 108, 110])

In [171]:
arr -= 100

In [172]:
arr

array([ 2,  4,  6,  8, 10])

In [173]:
arr /= 2

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [174]:
arr = arr.astype('float')

In [175]:
arr /= 2

In [176]:
arr

array([1., 2., 3., 4., 5.])

In [177]:
arr = arr.astype('int')

In [178]:
arr

array([1, 2, 3, 4, 5])

In [179]:
#CLIP
arr *= 2

In [180]:
arr

array([ 2,  4,  6,  8, 10])

In [183]:
arr = np.clip(arr, 3, 8)

In [184]:
arr

array([3, 4, 6, 8, 8])

In [185]:
arr = np.arange(1,10)

In [186]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
arr = np.clip(arr, 3, 8)

In [188]:
arr

array([3, 3, 3, 4, 5, 6, 7, 8, 8])

In [189]:
#indices
arr = np.arange(1,6)*10

In [190]:
arr

array([10, 20, 30, 40, 50])

In [192]:
indices = [0,2,4]

In [193]:
arr[indices] = -1

In [194]:
#[-1, 20, -1, 40, -1]
arr

array([-1, 20, -1, 40, -1])

In [195]:
arr = np.arange(1,6)*10

In [196]:
ind = [True, False, True, False, True]

In [197]:
ind

[True, False, True, False, True]

In [198]:
arr[ind]

array([10, 30, 50])

In [200]:
arr[ind] = [100, 300, 500]

In [201]:
arr

array([100,  20, 300,  40, 500])

In [202]:
arr[0], arr[2], arr[4] = 100, 300, 500

In [203]:
arr

array([100,  20, 300,  40, 500])

In [204]:
mask = arr > 99

In [205]:
arr[mask] = arr[mask]/100

In [206]:
arr

array([ 1, 20,  3, 40,  5])

In [207]:
mask10 = arr > 10

In [208]:
arr[mask10] = arr[mask10]/10

In [209]:
arr

array([1, 2, 3, 4, 5])

In [210]:
arr[mask10] = arr[mask10]/10

In [211]:
arr

array([1, 0, 3, 0, 5])

In [212]:
mask10

array([False,  True, False,  True, False])

In [215]:
arr[arr > 10] = arr[mask]/2

ValueError: NumPy boolean array indexing assignment cannot assign 3 input values to the 0 output values where the mask is true

In [214]:
arr

array([1, 0, 3, 0, 5])

In [216]:
arr[mask]/2

array([0.5, 1.5, 2.5])

In [217]:
arr[arr > 10]

array([], dtype=int32)

In [218]:
arr[arr > 10] = arr[mask]/2

ValueError: NumPy boolean array indexing assignment cannot assign 3 input values to the 0 output values where the mask is true

In [223]:
if len(arr[arr > 10]) > 0:
    arr[arr > 10] = arr[mask] + 2
else:
    print("Nothing happened")

Nothing happened


In [220]:
arr

array([1, 0, 3, 0, 5])

In [221]:
len(arr[arr > 10])

0

In [224]:
arr[arr > 10] = arr[mask] + 2
    

ValueError: NumPy boolean array indexing assignment cannot assign 3 input values to the 0 output values where the mask is true

In [226]:
try:
    arr[arr > 10] = arr[mask] + 2
except:
    print("failure")

failure


In [230]:
try:
    arr[arr > 10] = arr[mask] + 2
except Exception as e:
    print(f"Error occurred: {type(e).__name__}")
    print(f"Message: {str(e)}")

Error occurred: ValueError
Message: NumPy boolean array indexing assignment cannot assign 3 input values to the 0 output values where the mask is true


In [231]:
try:
    arr[arr > 10] = arr[mask] + 2
# except Exception as e:
#     print(f"Error occurred: {type(e).__name__}")
#     print(f"Message: {str(e)}")
except IndexError as e:
    print("Shape mismatch error - check your array dimensions")
except ValueError as e:
    print("Value-related error - check your input values")
except TypeError as e:
    print("Type-related error - check your data types")
except Exception as e:
    print(f"Unexpected error: {type(e).__name__}")

Value-related error - check your input values


In [232]:
data = np.array([5,10,15, 20, 25])
mask = np.array([True, False, True, False, True])


In [233]:
#safe assignment
data[mask] = [50, 150, 250]

In [235]:
#complex conditional modification
data[(data > 10) & (data < 30)] = 999

In [236]:
data

array([ 50,  10, 150, 999, 250])