# Section 07 03 concatenation

#### Basic Concatenation(np.concatenate)

In [1]:
#1.1 Joining 1D Arrays

In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
#join as is:
result = np.concatenate((a,b))
print(result)

[1 2 3 4 5 6]


In [7]:
res = np.concatenate((a,b), axis=0)
print(result)


[1 2 3 4 5 6]


In [9]:
res.shape


(6,)

In [12]:
#Joining 2D arrays
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6]])
#Vertical stacking (axis=0)
v_stack = np.concatenate((arr1, arr2), axis=0)
print(v_stack)
#similar to inserting a row in a table

[[1 2]
 [3 4]
 [5 6]]


In [14]:
print(arr1)

[[1 2]
 [3 4]]


In [15]:
print(arr2)

[[5 6]]


In [16]:
print(v_stack)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
#Horizontal stacking (axis=1)
arr3 = np.array([[7], [8]])
h_stack = np.concatenate((arr1, arr3), axis=1)
print(h_stack)

[[1 2 7]
 [3 4 8]]


In [20]:
print(arr1)

[[1 2]
 [3 4]]


In [21]:
#Horizontal stacking (axis=1)
arr3 = np.array([[7,9,10], [8,10,10]])
h_stack = np.concatenate((arr1, arr3), axis=1)
print(h_stack)

[[ 1  2  7  9 10]
 [ 3  4  8 10 10]]


### Convenience Functions

In [22]:
#Vstsack

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])

#Convert 1D to 2D and stack Vertically
result = np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


In [24]:
#hstack

In [25]:
a = np.array([[1],[2]])
b = np.array([[3], [4]])

#stack horizontally
result = np.hstack((a, b))
print(result)

[[1 3]
 [2 4]]


In [26]:
# Depth-wise stacking (dstack)
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [27]:
#stack along third dimension
result = np.dstack((a,b))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [28]:
#Advanced Stacking np.stack

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])
#stack along a new axis (default is axis=0)
result = np.stack((a, b))

In [30]:
print(result)

[[1 2 3]
 [4 5 6]]


In [31]:
#Stack along second axis
result = np.stack((a, b), axis=1)
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [32]:
#Stack along 3rd d
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
result = np.stack((a, b), axis=2)
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


### Machine learning use

In [34]:
features1 = np.random.rand(22, 5)  # First set of features
features2 = np.random.rand(22, 3)  # Second set

# Combine features horizontally
X = np.hstack((features1, features2))
print(X.shape)  # (100, 8)

(22, 8)


In [36]:
#Time Series Data
time_points = np.arange(10)
sensor1 = np.random.rand(10)
sensor2 = np.random.rand(10)

# Create multivariate time series
time_series = np.column_stack((time_points, sensor1, sensor2))
print(time_series.shape)  # (10, 3)

(10, 3)


# Section 07 04 

In [39]:
# Basic Splitting
import numpy as np
arr = np.arange(10)
print("arr : ", arr)

#split in two
result = np.split(arr, 2)
print(result)
result1 = result[0]
print(result1)

arr :  [0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[0 1 2 3 4]


In [40]:
# unequal division
#splitting at specific indices
arr = np.arange(10) 
result = np.split(arr, [3,7]) #split after index 3 and 7
for i in result:
    print(i)

[0 1 2]
[3 4 5 6]
[7 8 9]


In [42]:
# 2D array splitting (Advanced)
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
# Split vertically (rows)
result = np.split(arr_2d, 3, axis=0)
for i in result:
    print(i)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [44]:
#Split horizontally (column)
result = np.split(arr_2d, 3, axis=1)
for i in result:
    print(i)

[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [45]:
#Convenience functions
# hsplit Horizontal splitting 
arr = np.array([[1,2,3,4], [5,6,7,8]])

#split into 2 equal columns
result = np.hsplit(arr, 2)
print(result)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [46]:
#Split at specific indices
result = np.hsplit(arr, [1,3])
for i in result:
    print(i)

[[1]
 [5]]
[[2 3]
 [6 7]]
[[4]
 [8]]


In [47]:
#Vertical splitting
#vsplit
result = np.split(arr, 2)
for i in result:
    print(i)

[[1 2 3 4]]
[[5 6 7 8]]


In [48]:
# to split at specific indices
result = np.vsplit(arr, [1,3]) 
print(result)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int32)]


In [49]:
# Advanced Splitting techniques Optional
#Depth-wise splitting dsplit()

In [50]:
arr_3d = np.arange(8).reshape(2,2,2)

#Split along depth (3rd axis)
result = np.dsplit(arr_3d, 2)
for i in result:
    print(i)

[[[0]
  [2]]

 [[4]
  [6]]]
[[[1]
  [3]]

 [[5]
  [7]]]


In [51]:
#Array prtitioning (np.array_split)
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
#Split into 3 parts (uneven division allowd)
result = np.array_split(arr, 3)
for i in result:
    print(i)

[0 1 2 3]
[4 5 6]
[7 8 9]


#### Machine Learning

In [53]:
data = np.random.rand(100, 5)  # 100 samples, 5 features
train, test = np.split(data, [int(0.8*len(data))])
print(train.shape, test.shape)  # (80, 5), (20, 5)

(80, 5) (20, 5)


#### Time Series (Window splittin)


In [54]:
time_series = np.arange(100)
windows = np.split(time_series, range(10, 100, 10))
print(len(windows))  # 10 windows (9 of size 10, last of size 10)

10
